// 2026-10-09 验收修复：bench 覆盖 ai.memory.recallTimeoutMs=120s——生产的 4s 是交互预算，每题一组冷库的整组会话索引在 4s 内跑不完会让原文通道整组退化为空（测得冷启动伪影而非检索能力）；token 预算与 dreaming 截断不调整，生效值随报告 manifest 记录。sourceHash 按当前源码刷新。
// 2026-10-09 最终静态复核：空工具样本污染分账、真实多会话夹具及绑定式外判分回填已复核，覆盖声明同步；未执行测试。
import type { ModuleContract } from "../host/types"

export const memoryBenchContract: ModuleContract = {
  module: "memory-bench",
  sourceFiles: ["test/memory-bench/upstream-lock.json", "test/memory-bench/prepare.mjs", "test/memory-bench/index.mjs", "test/memory-bench/judge.mjs", "test/memory-bench/export-hypotheses.mjs", "test/memory-bench/import-verdicts.mjs", "test/memory-bench/report.mjs", "test/memory-bench/scope-normalize.mjs", "test/memory-bench/bench-adapter.ts", "test/memory-bench/reader-control.mjs", "test/memory-bench/datasets/longmemeval/importer.mjs", "test/memory-bench/datasets/longmemeval/scorer.mjs", "test/memory-bench/datasets/locomo/importer.mjs", "test/memory-bench/datasets/locomo/porter.mjs", "test/memory-bench/datasets/locomo/scorer.mjs", "test/memory-bench/datasets/memorybank/importer.mjs", "test/memory-bench/datasets/memorybank/scorer.mjs"],
  sourceHash: "99475a9fc1659e6b546685d5a6ed6c3cd1113d73a17686916bb75e4c75d4f996",
  coverage: [
    { id: "mb-07", feature: "外部判分回填与工具污染分账", description: "导出并校验 report/case/question/hypothesis 绑定，外部 yes/no 或官方 autoeval_label 必须有具名判分者、口径和时间；拒绝重复未知或错绑行，部分回填不混本地 verdict。按完整所选题集报告类型、失败、未知与严格空工具子集，助手题仍在总分；旧报告缺逐题类型保持未知。原始报告不覆盖，派生报告显示来源与判分审计。提问回合冻结 toolMode none，若出现工具调用仍保留回答并单独统计污染", why: "适配错误不能丢弃可能答对的样本，口头分数与无法绑定原回答的 verdict 不能成为可信结果", layer: "unit", depth: "deep", scenarios: ["bench-external-hypotheses-binding", "bench-external-score-roster", "bench-external-score-isolation", "bench-external-legacy-unknown-types", "bench-external-judge-identity", "bench-external-verdict-rejection", "bench-report-external-audit", "bench-lme-planned-tooling-breakdown"] },
    {"id": "mb-01", "feature": "版本锁定与安装器", "description": "上游 revision 与 SHA-256 全部固定且校验失败拒绝使用；仓库许可原文副本与锁定哈希逐字节一致（NC 合规红线）；数据一律不进仓库目录、按锁下载到 data-dir（可指定）", "why": "外部基准的权威性依赖「同一 revision + 同一校验和 = 同一份数据」；锁定失效或数据回流仓库会让复现性无声破裂", "layer": "unit", "depth": "deep", "scenarios": ["bench-lock-pinned", "bench-lock-license", "bench-lock-no-vendored-data"]},
    {"id": "mb-02", "feature": "数据形态与导入校验", "description": "上游形状漂移显式暴露（悬挂行容错、缺答案抛错、重复角色行抛错）；证据轮坐标与弃权标记可追溯；question_date 时间锚点按本地墙钟还原（不拿 UTC 毫秒冒充当地日期）；子集选择确定性且覆盖题型", "why": "静默容忍上游瑕疵会让评测在错的坐标上跑出看似正常的结果", "layer": "unit", "depth": "deep", "scenarios": ["bench-lme-subset", "bench-lme-source-coords", "bench-lme-question-anchor", "bench-locomo-tolerance", "bench-membank-dup-guard"]},
    {"id": "mb-03", "feature": "判分模板与解析", "description": "LongMemEval 官方五套模板逐字移植与按题型分流（弃权优先级最高）；yes 解析与官方一致；槽位替换防串位；judge 输出预算给 reasoning 留思考空间且不回退到截断的固定值", "why": "判分模板一旦偏离官方口径，分数就不再可比，「权威」标签失效；判分被输出上限截断会变成静默未裁决", "layer": "unit", "depth": "deep", "scenarios": ["bench-judge-routing", "bench-judge-abstention", "bench-judge-verbatim", "bench-judge-parse", "bench-judge-budget"]},
    {"id": "mb-04", "feature": "LoCoMo 确定性判分", "description": "Porter 词干 + 多集词频交集 F1；多跳按子句取最优；对抗题官方措辞二值；未登记 category 抛错不静默计 0", "why": "免 judge 的确定性判分是第二数据集的可信来源，口径漂移与静默兜底都会伪造分数", "layer": "unit", "depth": "deep", "scenarios": ["bench-locomo-multihop-f1", "bench-locomo-adversarial"]},
    {"id": "mb-05", "feature": "runner 与观测隔离", "description": "报告顶层 external/observational/阈值 null（passed 仅表示完整跑完）；judge 异构纪律两段生效：缺 judgeModel 在开跑前抛错，同模型自评在判分解析时被拒绝并如实记为未裁决（不静默自评）；连续基础设施失败中止并如实记录；分组连续与 limit 截断语义", "why": "外部基准是观测性证据：它不得冒充质量门禁，也不得在自评或静默中止下产出看起来完成的结论", "layer": "unit", "depth": "deep", "scenarios": ["bench-report-observational", "bench-judge-model-required", "bench-runner-abort", "bench-runner-group-order"]},
    {"id": "mb-06", "feature": "夹具 session→user 归一", "description": "仅非 LongMemEval 的直接事实夹具做 session→user 归一；LongMemEval 保留真实多会话转写与自然产品范围，不做 add/forget 归一以免误伤助手引用锚。归一时先全部 add、再全部 forget：Rust 的遗忘墓碑会拒绝之后任何引用同一来源的新增，逐条交错会在共享来源的候选上把整题打成「来源未登记」的基础设施失败；规划只挑 active/session 条目，副本改 user 范围且不携带 scopeId", "why": "外部基准的失败必须归因到被测能力，而不是夹具自己撞产品治理规则的假故障；顺序错了会让个别整题静默变成基础设施失败、分布失真", "layer": "unit", "depth": "deep", "scenarios": ["bench-scope-normalize-order"]},
    {"id": "mb-08", "feature": "Privileged full-evidence reader control", "description": "LongMemEval oracle eval-only direct/CoN controls保留所有 supplied session 的角色与日期并排除答案标签；note 与最终回答使用解析后生产模型输出预算，截断或空生成记为失败。报告标记 privileged/non-product-score；超出上下文预算时失败而不静默裁剪", "why": "隔离 reader 能力与产品检索，同时避免标签泄漏、输出预算截断或隐式上下文裁剪伪造上限结果", "layer": "unit", "depth": "deep", "scenarios": ["bench-reader-control-gold-isolation", "bench-reader-control-role-time-preservation", "bench-reader-control-output-failure"]},
  ],
  rules: { minScenarios: 0, minDeepScenarios: 0, requireBoundary: false, requireErrorPath: false },
}
