import type { ModuleContract } from "../host/types"

export const observationContract: ModuleContract = {
  module: "observation",
  sourceFiles: [
    "src/services/observation/index.ts",
    "src/services/observation/types.ts",
    "src/services/observation/store.ts",
    "src/services/observation/topics.ts",
    "src/services/observation/scheduler.ts",
    "src/services/observation/ownership.ts",
    "src/services/observation/picker.ts",
    "src/services/observation/config.ts",
    "src/services/config.ts",
    "src/services/proactive/config.ts",
    "src/services/behavior/collector.ts",
    "src/services/window/listener.ts",
    "src/services/window/monitor.ts",
    "src/services/window/index.ts",
    "src/services/engine/harness/model-gateway.ts",
    "src/services/context/budget.ts",
    "src/services/images/budget.ts",
    "src/services/images/limits.json",
    "src/services/engine/runtime/snapshot.ts",
    "src/services/engine/harness/runtime.ts",
    "src/services/engine/harness/index.ts",
    "src/services/engine/runtime/types.ts",
    "src/services/agent/runner.ts",
    "src/services/agent/memory/ipc.ts",
    "src/services/proactive/content/pool.ts",
    "src/services/proactive/auxiliary-budget.ts",
    "src-tauri/src/proactive/schema.rs",
    "src-tauri/src/proactive/store.rs",
    "src-tauri/src/proactive/commands.rs",
    "src-tauri/src/commands/observation_cmd.rs",
    "src-tauri/src/commands/mod.rs",
    "src-tauri/src/lib.rs",
    "src-tauri/src/error.rs",
    "src-tauri/src/paths/security.rs",
    "src-tauri/src/monitor/mod.rs",
    "src-tauri/Cargo.toml",
    "Cargo.lock",
    "src/App.vue",
    "src/components/settings/AITab.vue",
    "src/components/settings/SettingsPanel.vue",
    "test/integration/observation/了解层与话题来源.test.ts",
    "test/e2e/scenes/observation/静默访问关闭边界.scene.ts",
  ],
  sourceHash: "10210e475ca2419c8c810c3d090c8d5e0b21c2127a7e36bb61f386fb54a968ee",
  coverage: [
    {
      id: "ob-01",
      feature: "了解层来源、TTL、关闭与清除水位",
      description: "了解层只返回未过期的截图/文件/窗口摘要和来源身份；少于3条有效来源保持thin，关闭许可不向请求暴露观察；clear等待在途任务与入队写完成、撤掉摘要/标签，并持久化topic source watermark，提交前产生的老用户entry即使被普通回合补扫也不能回灌。Node集成只证明现有文件IPC/RAM语义，不假冒Rust截图和文件路径裁决。",
      why: "观察来源是可撤销派生资料，不能在关闭时进入模型，也不能在清除后被迟到任务或忙碌收件箱扫描复活。",
      layer: "integration",
      depth: "deep",
      scenarios: ["observation-understanding-ttl-clear"],
    },
    {
      id: "ob-02",
      feature: "话题画像的可信用户来源与失效",
      description: "只接受已提交origin=user、taint=trusted_user且eligibleForMemory的用户entry；话题辅助请求无tools，正文只在本次请求RAM中使用，持久层只含标签、权重、哈希sourceId、时间与Card失效范围。独立参与source达到2条后才向主动选材公开；标签source证据最多512条且自然保留90日；取消/清除/entry失效阻止旧标签回写。",
      why: "单次提及不等于偏好，工具/外部内容不具备用户来源资格；已遗忘或清除的话题不能继续驱动主动选材。",
      layer: "integration",
      depth: "deep",
      scenarios: ["observation-topic-trust-cancel", "observation-topic-revoked-before-provider", "observation-topic-large-batch-progress"],
    },
    {
      id: "ob-03",
      feature: "Rust观察命令的许可终裁",
      description: "静默访问关闭时，真实Rust注册的截图和有限项目文件命令返回CANCELLED，系统窗口观察显示disabled；前端关闭只能阻止调度，最终权限由原生MonitorState裁决。",
      why: "前端状态或漏接的后台任务不能绕过用户关闭许可，原生边界必须阻止截图和文件读取。",
      layer: "e2e",
      depth: "deep",
      scenarios: ["observation-native-disabled-boundary"],
    },
  ],
  rules: { minScenarios: 1, minDeepScenarios: 1, requireBoundary: true, requireErrorPath: true },
}
