// Generated by scripts/generate-memory-protocol.mjs. Do not edit.

pub const MEMORY_COMMANDS: &[&str] = &["memory_status", "memory_list", "memory_detail", "memory_register_sources", "memory_query", "memory_get_items", "memory_apply_change", "memory_job_start", "memory_job_checkpoint", "memory_job_cancel", "memory_job_resume", "memory_job_sources", "memory_candidates_add", "memory_review_batch", "memory_publish_batch", "memory_export", "memory_backup", "memory_rebuild", "memory_restore"];
pub const MEMORY_SCHEMA_VERSION: i64 = 1;
