// Generated by scripts/generate-memory-protocol.mjs. Do not edit.

pub const MEMORY_COMMANDS: &[&str] = &["memory_recall_candidates", "memory_job_list", "memory_restore_preview", "memory_source_evidence", "memory_status", "memory_list", "memory_detail", "memory_history", "memory_register_sources", "memory_query", "memory_get_items", "memory_apply_change", "memory_job_start", "memory_job_checkpoint", "memory_job_cancel", "memory_job_resume", "memory_job_sources", "memory_candidates_add", "memory_dreaming_commit", "memory_dreaming_budget_reserve", "memory_dreaming_budget_settle", "memory_dreaming_budget", "memory_export", "memory_backup", "memory_rebuild", "memory_restore"];
pub const PROACTIVE_COMMANDS: &[&str] = &["proactive_scan", "proactive_query", "proactive_change", "proactive_claim", "proactive_validate", "proactive_settle", "proactive_reconcile", "proactive_control"];
pub const MEMORY_SCHEMA_VERSION: i64 = 2;
pub const PROACTIVE_TICK_MS: i64 = 300000;
pub const PROACTIVE_QUIET_START_HOUR: i64 = 22;
pub const PROACTIVE_QUIET_END_HOUR: i64 = 9;
pub const PROACTIVE_DAILY_SUCCESS: i64 = 1;
pub const PROACTIVE_DAILY_EXPRESSION_ATTEMPTS: i64 = 3;
pub const PROACTIVE_DAILY_PLANNING_ATTEMPTS: i64 = 2;
pub const PROACTIVE_DAILY_TOKENS: i64 = 24000;
pub const PROACTIVE_MAX_TASKS: i64 = 100;
pub const PROACTIVE_MAX_RECURRING_TASKS: i64 = 10;
pub const PROACTIVE_MAX_TASKS_PER_PLAN: i64 = 2;
pub const PROACTIVE_MAX_TARGETS_PER_MESSAGE: i64 = 2;
pub const PROACTIVE_SCAN_BATCH: i64 = 100;
pub const PROACTIVE_RETRY_DELAY_MS: i64 = 1800000;
pub const PROACTIVE_ATTEMPT_LEASE_MS: i64 = 180000;
pub const PROACTIVE_EVALUATION_RETENTION_DAYS: i64 = 30;
pub const PROACTIVE_SETTLED_RETENTION_DAYS: i64 = 90;
