import type { ModuleContract } from "../types"

export const agentRuntimeContract: ModuleContract = {
  module: "agent-runtime",
  sourceFiles: [
    "src/services/agent/runner.ts",
    "src/services/debug.ts",
    "src/services/engine/pi/harness-slot.ts",
    "src/services/engine/pi/model-gateway.ts",
    "src/services/engine/pi/runtime.ts",
    "src/services/engine/preprocessor.ts",
    "src/services/session/manager.ts",
    "src/services/session/persistence.ts",
    "src/services/session/repo.ts",
  ],
  generatedAt: "2026-09-20",
  sourceHash: "0727e76de200491b1098aa4848fa965adc6ab190b95e0898d3089514f07fd2e4",
  coverage: [
    {
      id: "ar-01",
      feature: "生产消息入口",
      description: "sendMessage 经预处理、Harness lane 与会话条目持久化走完一个回合；用户正文与助手回复都能按会话 id 从 JSONL 读回恰好一次",
      why: "直接调用运行内核不能证明桌宠实际聊天入口仍然可用",
      depth: "deep",
      scenarios: ["production-chat-entry"],
    },
    {
      id: "ar-02",
      feature: "工具期间的输入先进入 lane 持久 inbox",
      description: "工具执行期间的新输入以 steer 进入 lane 持久 inbox（队列快照可见），消费后正文恰好一次且排在工具结果之后",
      why: "先落盘再影响模型是 H-4 的投递不变量；宿主自建队列删除后只剩这一条路径",
      depth: "deep",
      scenarios: ["memory-steer-during-tool"],
    },
    {
      id: "ar-03",
      feature: "followUp 通道语义",
      description: "以 followUp 入队的收尾输入由本次运行继续处理，正文恰好一次且排在首个回复之后；工具执行期（streaming）的投递模式必须是 steer，不得冒充 followUp",
      why: "followUp 语义不能被 steer 混淆，也不能在自然结束边界丢输入。注：settling 窗口由 Harness 的 turn_end 事件驱动、无法在场景里稳定命中（旧内核的 markDeliveryPhase 入口已随迁移删除），因此本覆盖点验证的是 followUp 通道自身的语义与 streaming 侧的投递模式判定，不声称验证了 settling 自动路由",
      depth: "deep",
      scenarios: ["memory-followup-after-turn"],
    },
    {
      id: "ar-04",
      feature: "会话运行槽代际所有权",
      description: "主回合按 sessionId 持有运行槽；代际单调，旧代际不能结束新 run，槽被释放重建后代际也不回退（ABA），并发 drain 复用同一 worker",
      why: "没有代际守卫时迟到的 cleanup 会结束或清空重建后的新运行",
      depth: "deep",
      scenarios: ["session-harness-slot-generation"],
    },
    {
      id: "ar-05",
      feature: "停止归还",
      description: "显式停止归还未消费输入：以 nextRun 持久保留、不自动继续执行，恢复运行时恰好消费一次",
      why: "停止不能丢用户输入，也不能替用户自动继续剩余话题",
      depth: "deep",
      scenarios: ["runtime-stop-requeue"],
    },
    {
      id: "ar-06",
      feature: "nextRun 持久 inbox",
      description: "忙碌期间的下一轮输入（如未识别 slash 文本）以 nextRun 入队，不被当前运行消费，下一次运行接受后按序进入上下文",
      why: "排队输入必须有持久归宿且不重复追加用户正文",
      depth: "deep",
      scenarios: ["runtime-nextrun-inbox"],
    },
    {
      id: "ar-07",
      feature: "用量按 purpose 分列",
      description: "主回合逐请求 usage 记入 main 分项；规划等一次性调用（压缩走同一通道）按自己的 purpose 单独计数，不覆盖主回合的 last/上下文统计，也不计入 main；总量由各分项相加，未回报 usage 的失败调用只计次数",
      why: "一次性调用既不能冒充主回复统计，也不能从总消耗里消失；分别只累加数字会让总量与分项对不上",
      depth: "deep",
      scenarios: ["runtime-usage-purpose-split"],
    },
    {
      id: "ar-08",
      feature: "显式投递意图与排队视图",
      description: "忙碌时显式选择插话/稍后继续的投递回执与 lane inbox 的 kind 一致（steered/followup），排队视图（listQueuedInputs）按序给出 kind 与正文；单项撤回仍在 inbox 的项返回 cancelled 且不再进入对话，已消费项返回 already_consumed，运行结束后队列为空",
      why: "投递意图必须由用户显式选择而不是由运行阶段决定；排队状态与撤回结果不能虚构，否则用户会把「已排队」当成「已处理」",
      depth: "deep",
      scenarios: ["runtime-delivery-intent"],
    },
  ],
  rules: { minScenarios: 6, minDeepScenarios: 6, requireBoundary: true, requireErrorPath: false },
}

export default agentRuntimeContract
