import type { ModuleContract } from "../types"

export const memoryContract: ModuleContract = {
  module: "memory",
  sourceFiles: [
    "src/services/agent/memory/index.ts",
    "src/services/agent/memory/io.ts",
    "src/services/agent/memory/memory-entries.ts",
    "src/services/agent/memory/consolidate.ts",
    "src/services/agent/memory/parsers.ts",
    "src/services/agent/memory/plan-checkpoint-store.ts",
    "src/services/agent/memory/provider.ts",
    "src/services/agent/memory/compaction-store.ts",
    "src/services/engine/runtime/snapshot.ts",
    "src/services/engine/runtime/types.ts",
    "src/services/engine/runtime/trace.ts",
    "src/services/engine/pi/runtime.ts",
    "src/services/engine/pi/model-gateway.ts",
    "src/services/engine/pi/harness-slot.ts",
    "src/services/engine/compactor.ts",
    "src/services/context/builder.ts",
    "src/services/context/kernel.ts",
    "src/services/context/projection.ts",
    "src/services/context/budget.ts",
    "src/services/context/rounds.ts",
    "src/services/context/tool-output.ts",
  ],
  generatedAt: "2026-09-18",
  sourceHash: "10161dee4c40756e873a35c918bf3bfaf47059ff9ab2277b792bc24e25297d9e",
  coverage: [
    { id: "mm-01", feature: "Memory 添加条目", description: "MemoryService.append() 创建记忆", why: "记忆系统基础 CRUD", depth: "shallow", scenarios: ["memory-append"] },
    { id: "mm-02", feature: "Memory 搜索", description: "MemoryService.search(query, limit) 按内容搜索", why: "LLM 需检索相关记忆", depth: "shallow", scenarios: ["memory-search"] },
    { id: "mm-03", feature: "Memory 重要性过滤", description: "MemoryService.important(threshold) 过滤", why: "prompt 注入按重要性裁剪", depth: "shallow", scenarios: ["memory-important"] },
    { id: "mm-04", feature: "Memory 更新/删除", description: "MemoryService.update/remove 生命周期", why: "记忆管理", depth: "shallow", scenarios: ["memory-update-remove"] },
    { id: "mm-06", feature: "本地整理 Consolidate", description: "MemoryService.checkAndConsolidate() 只做本地去重，不隐式请求 LLM", why: "后台维护不能抢占首答或未经授权提取长期事实", depth: "shallow", scenarios: ["memory-consolidate"] },
    { id: "mm-07", feature: "Candy/User 指令", description: "getCandyInstructionsSync/getUserProfileSync 返回指令", why: "prompt 注入的记忆内容", depth: "shallow", scenarios: ["memory-system-files"] },
    { id: "mm-08", feature: "多轮会话条目持久化", description: "真实多轮对话后可按 sessionId 从 sessions/ 下的 JSONL 读回完整换行正文；后续回合只新增条目不重放历史", why: "会话条目是真相源，UI 切换或重载不能改变读取目标", depth: "deep", scenarios: ["memory-multi-turn"] },
    { id: "mm-11", feature: "PromptSnapshot", description: "transformContext 后与 Provider payload 双快照可关联 request/turn/run；派生 rewrite 只保存 hash", why: "上下文审计不能泄露原始 prompt、覆盖用户原文或把估算 token 当成实际 usage", depth: "deep", scenarios: ["memory-prompt-snapshot"] },
    { id: "mm-12", feature: "主动消息来源", description: "主动搭话落成 deskpet.active_message 条目（active 来源、eligibleForMemory=false），不进入聊天视图与用户事实", why: "系统上下文不能污染用户事实和长期记忆", depth: "deep", scenarios: ["memory-active-origin"] },
    { id: "mm-13", feature: "工具成对观测", description: "工具调用与结果按 id 配对保留在会话条目，并被 runtime history 观测", why: "后续压缩和恢复需要完整 tool pair 基线", depth: "deep", scenarios: ["memory-tool-pair-baseline"] },
    { id: "mm-15", feature: "Plan checkpoint 恢复", description: "运行中 Plan 从会话条目 deskpet.plan_checkpoint 恢复；只读步骤回到 pending，未知外部副作用进入 unknown_side_effect，恢复动作可条目回读", why: "进程重启后不能重复执行没有完成凭证的外部操作", depth: "deep", scenarios: ["memory-plan-resume"] },
    { id: "mm-16", feature: "ContextKernel 预算", description: "完整静态前缀、工具 schema 与当前会话视图按硬预算验证；可选投影整块降级", why: "Provider 输入需要可预测且可审计地限制在上下文窗口内，且不能静默丢失指令或未压缩历史", depth: "deep", scenarios: ["memory-context-budget"] },
    { id: "mm-17", feature: "画像与记忆投影", description: "User.md 使用带来源的只读 projection；MemoryProvider 可注入、取消、限时、裁剪并恢复，默认空实现不执行长期召回", why: "画像和长期事实需要显式来源边界，下一阶段选择存储与检索策略时不能改动 Agent Runtime", depth: "deep", scenarios: ["memory-profile-rewrite"] },
    { id: "mm-18", feature: "消息条目单次写入", description: "一次真实回合后同一句话只有一条 pi 会话条目；后续回合不重复追加历史消息", why: "双写或历史重放会让重载出现重复消息与翻倍轮数", depth: "deep", scenarios: ["memory-single-message-write"] },
    { id: "mm-19", feature: "Harness 压缩与摘要内核", description: "手动/阈值压缩由 Harness 调度：宿主 before_compaction 生成结构化摘要并提交 compaction 条目，原始消息条目全部保留，contextEpoch 推进", why: "摘要只能替换后续请求视图，不能删除会话真相源，也不能把压缩调度留在宿主第二套状态机里", depth: "deep", scenarios: ["memory-compaction-checkpoint"] },
    { id: "mm-20", feature: "上下文窗口下限", description: "低于 65536 的窗口被拒绝：设置保存报错、运行期在模型解析处报错，合法窗口照常解析且不超过配置值", why: "窗口过小时压缩找不到可摘要范围，静默接受只会把预算问题推迟成运行期的另一种报错", depth: "shallow", scenarios: ["memory-context-window-floor"] },
    { id: "mm-21", feature: "压缩阈值口径换算", description: "派生的 reserve/keepRecent 换算到上游 chars/4 估算口径：阈值落在本仓 normalInputTarget 上、先于宿主硬预算触发，保留窗口放得进消息空间", why: "上游按自己的估算比较阈值，不换算会让阈值晚约 1.6 倍触发，请求先撞宿主硬预算报错而不是先压缩", depth: "shallow", scenarios: ["memory-compaction-threshold-calibration"] },
  ],
  rules: { minScenarios: 6, minDeepScenarios: 2, requireBoundary: true, requireErrorPath: true },
}
