import type { ModuleContract } from "../types"

export const memoryContract: ModuleContract = {
  module: "memory",
  sourceFiles: [
    "src/services/agent/memory/index.ts",
    "src/services/agent/memory/io.ts",
    "src/services/agent/memory/memory-entries.ts",
    "src/services/agent/memory/consolidate.ts",
    "src/services/agent/memory/parsers.ts",
    "src/services/agent/memory/plan-checkpoint-store.ts",
    "src/services/agent/memory/provider.ts",
    "src/services/agent/memory/compaction-store.ts",
    "src/services/engine/runtime/snapshot.ts",
    "src/services/engine/runtime/types.ts",
    "src/services/engine/runtime/trace.ts",
    "src/services/engine/pi/runtime.ts",
    "src/services/engine/pi/model-gateway.ts",
    "src/services/engine/pi/harness-slot.ts",
    "src/services/engine/compactor.ts",
    "src/services/context/builder.ts",
    "src/services/context/kernel.ts",
    "src/services/context/projection.ts",
    "src/services/context/budget.ts",
    "src/services/context/tool-output.ts",
    "src/services/debug.ts",
  ],
  generatedAt: "2026-09-23",
  sourceHash: "5ce0fbd7574e50eeba6b98e0dc418250d3058b5991cc30c80087b83be3499130",
  coverage: [
    { id: "mm-01", feature: "Memory 添加条目", description: "MemoryService.append() 创建记忆", why: "记忆系统基础 CRUD", depth: "shallow", scenarios: ["memory-append"] },
    { id: "mm-02", feature: "Memory 搜索", description: "MemoryService.search(query, limit) 按内容搜索", why: "LLM 需检索相关记忆", depth: "shallow", scenarios: ["memory-search"] },
    { id: "mm-03", feature: "Memory 重要性过滤", description: "MemoryService.important(threshold) 过滤", why: "prompt 注入按重要性裁剪", depth: "shallow", scenarios: ["memory-important"] },
    { id: "mm-04", feature: "Memory 更新/删除", description: "MemoryService.update/remove 生命周期", why: "记忆管理", depth: "shallow", scenarios: ["memory-update-remove"] },
    { id: "mm-06", feature: "本地整理 Consolidate", description: "MemoryService.checkAndConsolidate() 只做本地去重，不隐式请求 LLM", why: "后台维护不能抢占首答或未经授权提取长期事实", depth: "shallow", scenarios: ["memory-consolidate"] },
    { id: "mm-07", feature: "Candy/User 指令", description: "getCandyInstructionsSync/getUserProfileSync 返回指令", why: "prompt 注入的记忆内容", depth: "shallow", scenarios: ["memory-system-files"] },
    { id: "mm-08", feature: "多轮会话条目持久化", description: "真实多轮对话后可按 sessionId 从 sessions/ 下的 JSONL 读回完整换行正文；后续回合只新增条目不重放历史", why: "会话条目是真相源，UI 切换或重载不能改变读取目标", depth: "deep", scenarios: ["memory-multi-turn"] },
    { id: "mm-11", feature: "PromptSnapshot", description: "transformContext 后与 Provider payload 双快照可关联 request/turn/run；派生 rewrite 只保存 hash；每条工具条目的 policyHash 取完整策略指纹 toolPolicyHash(tool)（工具身份与 permission/execution/context 各维度），策略任一维度变化都会改变快照身份；投递输入的 agentMessages id 用其 deskpetEventId（无身份的用位置号回退），请求与输入的关联可按身份核对", why: "上下文审计不能泄露原始 prompt、覆盖用户原文或把估算 token 当成实际 usage", depth: "deep", scenarios: ["memory-prompt-snapshot", "memory-snapshot-identity"] },
    { id: "mm-12", feature: "主动消息来源", description: "主动搭话落成 deskpet.active_message 条目（active 来源、eligibleForMemory=false），不进入聊天视图与用户事实", why: "系统上下文不能污染用户事实和长期记忆", depth: "deep", scenarios: ["memory-active-origin"] },
    { id: "mm-13", feature: "工具成对观测", description: "工具调用与结果按 id 配对保留在会话条目，并被 runtime history 观测", why: "后续压缩和恢复需要完整 tool pair 基线", depth: "deep", scenarios: ["memory-tool-pair-baseline"] },
    { id: "mm-15", feature: "Plan checkpoint 恢复", description: "运行中 Plan 从会话条目 deskpet.plan_checkpoint 按事件级证据折迭恢复，产出可处置的 paused 计划（只读步骤回 pending；有 tool_start 无 tool_end 的效果工具进 unknown_side_effect）；继续/丢弃由用户显式触发，未知副作用不自动重放，恢复动作可条目回读", why: "进程重启后不能重复执行没有完成凭证的外部操作", depth: "deep", scenarios: ["memory-plan-resume"] },
    { id: "mm-16", feature: "ContextKernel 预算", description: "完整静态前缀、工具 schema 与当前会话视图按硬预算验证；可选投影整块降级", why: "Provider 输入需要可预测且可审计地限制在上下文窗口内，且不能静默丢失指令或未压缩历史", depth: "deep", scenarios: ["memory-context-budget"] },
    { id: "mm-17", feature: "画像与记忆投影", description: "User.md 使用带来源的只读 projection；MemoryProvider 可注入、取消、限时、裁剪并恢复，默认空实现不执行长期召回", why: "画像和长期事实需要显式来源边界，下一阶段选择存储与检索策略时不能改动 Agent Runtime", depth: "deep", scenarios: ["memory-profile-rewrite"] },
    { id: "mm-18", feature: "消息条目单次写入", description: "一次真实回合后同一句话只有一条 pi 会话条目；后续回合不重复追加历史消息", why: "双写或历史重放会让重载出现重复消息与翻倍轮数", depth: "deep", scenarios: ["memory-single-message-write"] },
    { id: "mm-19", feature: "Harness 压缩与摘要内核", description: "手动/阈值压缩由 Harness 调度：宿主 before_compaction 生成结构化摘要并提交 compaction 条目，原始消息条目全部保留，contextEpoch 推进；摘要调用的 usage 落压缩条目并按 purpose 单列，不冒充主回合统计；摘要素材的 L0 投影与主请求同口径：resultProjection=preserve 的工具结果完整进入摘要请求，reference 的才被缩短并留下回读标记", why: "摘要只能替换后续请求视图，不能删除会话真相源，也不能把压缩调度留在宿主第二套状态机里；一次性摘要的成本既不能混进主回合统计，也不能在总量里消失", depth: "deep", scenarios: ["memory-compaction-checkpoint", "memory-summary-preserve-projection"] },
    { id: "mm-20", feature: "上下文窗口下限", description: "低于 65536 的窗口被拒绝：设置保存报错、运行期在模型解析处报错，合法窗口照常解析且不超过配置值", why: "窗口过小时压缩找不到可摘要范围，静默接受只会把预算问题推迟成运行期的另一种报错", depth: "shallow", scenarios: ["memory-context-window-floor"] },
    { id: "mm-21", feature: "压缩阈值口径换算", description: "派生的 reserve/keepRecent 换算到 Harness 的计数口径：阈值落在本仓 normalInputTarget 上、先于宿主硬预算触发，保留窗口放得进消息空间，且估算器偏差不越过硬预算余量", why: "Harness 的 shouldCompact 在会话存在 provider usage 时按真实 usage 计，本仓估算同为目标真实 token 口径；估算器偏差一旦吃掉硬预算与正常输入目标的差额，硬预算就会先于压缩报错", depth: "shallow", scenarios: ["memory-compaction-threshold-calibration"] },
    { id: "mm-22", feature: "硬预算超限的溢出恢复", description: "宿主 transform_context 核对出的硬预算超限经网关上报为 Provider 溢出响应，Harness 用宿主 before_compaction 摘要压缩后重试一次；超限请求不发给 Provider，压缩只改请求视图，原文条目始终保留。恢复用尽时按可解释的硬预算判定失败；上游因没有可安全摘要的范围 declined 时，失败分类保留上游文案，回复仍回落本回合的硬预算判定。本地预算判定的失败分类只由「它是本地判定」决定，不随判定文案里估算数字的形态漂移（长数字串里的 5xx/401/429 片段不算状态码，真正的状态码仍命中对应分桶）", why: "硬预算只是发送前的本地上限，直接终止回合会让 Harness 自带的一次性溢出恢复永远轮不到；恢复既不能改变会话真相源、不能把压缩挪到重试之后，也不能让用户丢掉可解释的预算判定，更不能把本地失败记成 Provider/认证/限流故障", depth: "deep", scenarios: ["memory-budget-overflow-recovery", "memory-budget-overflow-classification"] },
    { id: "mm-23", feature: "retain 保留守卫", description: "摘要范围覆盖声明 historyCompaction=retain 的工具调用配对时，宿主 before_compaction 内核 decline：不向模型发出摘要请求、不提交 compaction 条目、不推进换代身份，原文条目保持完整；注销 retain 声明后同一会话与同一载荷照常压缩", why: "宁可不压缩也不能把必须保留原文的调用配对静默摘要掉：覆盖边界一旦越过它，未覆盖历史就被模型输出的摘要顶替", depth: "deep", scenarios: ["memory-retain-guard"] },
    { id: "mm-26", feature: "估算器角色覆盖与偏差对账", description: "内容投影按角色表覆盖 compactionSummary/branchSummary/bashExecution/custom（摘要只计 summary 正文、excludeFromContext 的 bash 执行计 0），未知角色按整条估算并留痕；provider_usage 快照记录 tokenDrift（estimated/actual/ratio），超 ESTIMATE_DRIFT_WARN_RATIO 只 warn 与 trace 带 driftRatio，不改变预算判定", why: "估算器系统性漏算某类消息会让硬预算与压缩触发点整体漂移，估算与真实 usage 的偏差必须可见才能定位", depth: "deep", scenarios: ["memory-estimator-role-coverage"] },
    { id: "mm-27", feature: "L0 地址完整性", description: "有地址的工具结果在请求视图里带真实 eventId 且可回读；无地址的不写假 eventId 而标「不可回读」；主请求与摘要素材对同一消息的缩短结果逐字相同", why: "回读地址是模型从缩短结果回到真相源的唯一通道，假地址会让模型读到「当前会话没有此工具结果」", depth: "deep", scenarios: ["memory-l0-address-integrity"] },
    { id: "mm-24", feature: "审计落盘闭环", description: "审计条目只入队、由唯一 flush 入口在 lane 空闲时写入；失败条目保留并重试一次；槽关闭前 flush 且残留非空记 error；transform_context/provider_payload/provider_usage 三档快照在一轮 production 回合里各至少一条且释放槽后集合不变", why: "证据链的组成项不能在槽生命周期结束时静默消失，否则「请求发过什么」这件事在重启后不可查", depth: "deep", scenarios: ["memory-snapshot-audit-closure"] },
    { id: "mm-25", feature: "摘要降级显式 decline", description: "宿主摘要内核失败时钩子返回 decline 而非抛出：/compact 报 failed 并在用户可见文案里给出原因；不提交 compaction 条目；回合路径写 deskpet.compaction_declined 审计条目", why: "上游通用英文摘要一旦提交就成为后续所有回合唯一的历史视图且不可回滚，宁可不压缩也不落违反协议的历史", depth: "deep", scenarios: ["memory-compaction-degrade-declines"] },
  ],
  rules: { minScenarios: 6, minDeepScenarios: 2, requireBoundary: true, requireErrorPath: true },
}
