import type { ModuleContract } from "../types"

export const memoryContract: ModuleContract = {
  module: "memory",
  sourceFiles: [
    "src/services/agent/memory/index.ts",
    "src/services/agent/memory/io.ts",
    "src/services/agent/memory/memory-entries.ts",
    "src/services/agent/memory/session-files.ts",
    "src/services/agent/memory/parsers.ts",
    "src/services/agent/memory/events.ts",
    "src/services/agent/memory/queue-events.ts",
    "src/services/agent/memory/plan-checkpoint-store.ts",
    "src/services/agent/memory/provider.ts",
    "src/services/engine/runtime/snapshot.ts",
    "src/services/engine/runtime/types.ts",
    "src/services/engine/runtime/trace.ts",
    "src/services/engine/pi/runtime.ts",
    "src/services/context/builder.ts",
    "src/services/context/kernel.ts",
    "src/services/context/projection.ts",
  ],
  generatedAt: "2026-09-16",
  sourceHash: "136e894377ed06c2e52f577b437717e06774065cefb9368c33378ad197c0d66b",
  coverage: [
    { id: "mm-01", feature: "Memory 添加条目", description: "MemoryService.append() 创建记忆", why: "记忆系统基础 CRUD", depth: "shallow", scenarios: ["memory-append"] },
    { id: "mm-02", feature: "Memory 搜索", description: "MemoryService.search(query, limit) 按内容搜索", why: "LLM 需检索相关记忆", depth: "shallow", scenarios: ["memory-search"] },
    { id: "mm-03", feature: "Memory 重要性过滤", description: "MemoryService.important(threshold) 过滤", why: "prompt 注入按重要性裁剪", depth: "shallow", scenarios: ["memory-important"] },
    { id: "mm-04", feature: "Memory 更新/删除", description: "MemoryService.update/remove 生命周期", why: "记忆管理", depth: "shallow", scenarios: ["memory-update-remove"] },
    { id: "mm-05", feature: "对话轮次记录", description: "MemoryService.recordTurn(role, text) 记录轮次", why: "session turn count 递增", depth: "deep", scenarios: ["memory-record-turn"] },
    { id: "mm-06", feature: "整理 Consolidate", description: "MemoryService.checkAndConsolidate() 定期整理", why: "防止记忆膨胀", depth: "shallow", scenarios: ["memory-consolidate"] },
    { id: "mm-07", feature: "Candy/User 指令", description: "getCandyInstructionsSync/getUserProfileSync 返回指令", why: "prompt 注入的记忆内容", depth: "shallow", scenarios: ["memory-system-files"] },
    { id: "mm-08", feature: "多轮会话 Markdown 持久化", description: "真实多轮对话后可按 sessionId 读取正文；异步摘要只写回捕获的会话和版本", why: "文件是会话真相源，异步任务不能随 UI 会话切换改变写入目标", depth: "deep", scenarios: ["memory-multi-turn"] },
    { id: "mm-09", feature: "会话事件序列化", description: "serializeSessionEvent() 生成可读预览和无损 deskpet-event JSON", why: "新事件协议必须保留可读性与完整字段", depth: "shallow", scenarios: ["memory-event-serialization"] },
    { id: "mm-10", feature: "旧会话事件兼容解析", description: "parseSessionEventsFromRaw() 兼容 deskpet-turn 与纯预览并报告损坏记录", why: "迁移期间不能丢失历史会话或静默吞掉损坏数据", depth: "deep", scenarios: ["memory-old-session-compat"] },
    { id: "mm-11", feature: "PromptSnapshot", description: "transformContext 后与 Provider payload 双快照可关联 request/turn/run；派生 rewrite 只保存 hash", why: "上下文审计不能泄露原始 prompt、覆盖用户原文或把估算 token 当成实际 usage", depth: "deep", scenarios: ["memory-prompt-snapshot"] },
    { id: "mm-12", feature: "主动消息来源", description: "主动搭话保持 active 来源，不写入 user 事实", why: "系统上下文不能污染用户事实和长期记忆", depth: "deep", scenarios: ["memory-active-origin"] },
    { id: "mm-13", feature: "工具成对观测", description: "工具调用与结果均可从 trace 和 runtime history 观察", why: "后续压缩和恢复需要完整 tool pair 基线", depth: "deep", scenarios: ["memory-tool-pair-baseline"] },
    { id: "mm-14", feature: "队列恢复与幂等", description: "queued 事件重启后可 requeue，requestId 不重复投递", why: "输入不能因进程中断丢失或重复执行", depth: "deep", scenarios: ["queued-recovery"] },
    { id: "mm-15", feature: "Plan checkpoint 恢复", description: "运行中 Plan 从 session event 恢复；只读步骤回到 pending，未知外部副作用进入 unknown_side_effect", why: "进程重启后不能重复执行没有完成凭证的外部操作", depth: "deep", scenarios: ["memory-plan-resume"] },
    { id: "mm-16", feature: "ContextKernel 预算", description: "六层上下文顺序固定，预算不足时记录结构化裁剪原因", why: "Provider 输入需要可预测且可审计地限制在上下文窗口内", depth: "deep", scenarios: ["memory-context-budget"] },
    { id: "mm-17", feature: "画像与记忆投影", description: "User.md 使用带来源的只读 projection；MemoryProvider 可注入、取消、限时、裁剪并恢复，默认空实现不执行长期召回", why: "画像和长期事实需要显式来源边界，下一阶段选择存储与检索策略时不能改动 Agent Runtime", depth: "deep", scenarios: ["memory-profile-rewrite"] },
    { id: "mm-18", feature: "正文记录单次写入", description: "一次真实回合后同一句话只有一条 deskpet-turn 记录；user_message 事件由 turn 记录投影得到，不再同时写 deskpet-event", why: "消息双写会让重载按预览和事件各重放一次，造成重复消息与翻倍轮数", depth: "deep", scenarios: ["memory-single-message-write"] },
  ],
  rules: { minScenarios: 6, minDeepScenarios: 2, requireBoundary: true, requireErrorPath: true },
}
