import type { ModuleContract } from "../types"

export const safetyContract: ModuleContract = {
  module: "safety",
  sourceFiles: ["src/services/engine/pi/runtime.ts", "src/services/engine/pi/harness-slot.ts", "src/services/safety/checker.ts", "src/services/safety/permission.ts", "src/services/safety/confirm.ts", "src/services/tool/types.ts", "src/services/tool/policy.ts", "src/services/tool/local/pi-tools.ts", "src/services/tool/local-extra/clipboard.ts", "src/services/tool/local-extra/agent-tool.ts", "src/services/tool/local-extra/app.ts", "src/services/tool/mcp/client.ts", "src/services/session/manager.ts", "src-tauri/src/paths.rs", "src-tauri/src/commands/bash_policy.rs", "src-tauri/src/commands/tool_exec.rs"],
  generatedAt: "2026-09-26",
  sourceHash: "8507e7775515e69f5d46f24dfbbcdae85448721f08dc30e8de0ed66b21215455",
  coverage: [
    { id: "sf-01", feature: "SAFE 级别放行", description: "safetyLevel=SAFE 的工具经生产裁决入口 evaluateToolPermission（标准决策层即 allow）直接放行，不生成确认请求；同一分支现在也接住 NORMAL，会话信任与安全裁决只有 permission.ts 一份实现", why: "安全等级体系基础，且放行结论必须来自唯一裁决点", depth: "shallow", scenarios: ["safety-safe"] },
    { id: "sf-02", feature: "统一裁决表（SAFE / NORMAL 一律放行）", description: "标准决策是安全等级到裁决结果的唯一映射：NOWAY → deny（最前置，先于安全模式与工具侧策略）；SAFE 与 NORMAL → allow（与安全模式无关，也不看命令是否在白名单里 —— 白名单只决定 NORMAL/DANGER 的归属，是免确认通道而不是拒绝依据）；DANGER → 交给回合冻结的安全模式（let_me_tk → ask、just_do_it → allow、其余含缺省 → ask）。工具与运行模式不再参与裁决：pet/assistant 双模式、lightweightPolicy、`ToolDef.mode`/`ToolContext.mode` 已全链删除，而旧助手下 NORMAL 没有任何 allow 路径、一律 ask —— 这条收紧的消失正是 sf-21 必须逐工具重定级的原因", why: "常规工具需要安全评估，且裁决表必须唯一：NORMAL 的归属翻转后若仍留旧描述，重定级与确认通道的场景会照着已不存在的分支写断言", depth: "shallow", scenarios: ["safety-normal"] },
    { id: "sf-03", feature: "DANGER 级别按安全模式裁决", description: "safetyLevel=DANGER（含路径分级提上来的敏感路径与危险命令）不在标准决策里直接放行或拒绝，而是交给回合冻结的安全模式：let_me_tk → ask、just_do_it → allow、其余（含缺省）→ ask；**DANGER 没有 deny 归宿** —— 拒绝只来自 NOWAY、工具侧 defaultDecision: 'deny'、不可用身份与「用户拒绝/确认过期」。走到 ask 时生成确认请求（身份 = sessionId + runGeneration + toolCallId，带 inputHash 与 policyHash），确认后重新评估参数与策略哈希，任一项变化都不复用旧授权；用户批准且选 allow_session 时按会话信任开关入账；测试宿主按场景声明的策略确定性应答（默认拒绝）。旧机制（lightweightPolicy 的 confirm/deny、助手模式弹窗、轻量模式按策略硬拒）已删，「没有确认通道就拒绝」的语义随之消失，所以 DANGER 在默认安全模式下的结论是 ask 而不是 deny", why: "危险操作需确认，且确认通道不得挂起；裁决表变了而描述仍写「轻量模式拒绝」，重写场景时会照着已不可达的 deny 分支写断言", depth: "deep", scenarios: ["safety-danger", "safety-confirm-denied", "safety-confirm-approved"] },
    { id: "sf-04", feature: "NOWAY 直接拒绝", description: "safetyLevel=NOWAY 在标准决策最前置的一步被拒绝（先于风险到安全模式的映射与工具侧策略），结论与安全模式、会话信任都无关", why: "绝对不允许的操作", depth: "shallow", scenarios: ["safety-noway"] },
    { id: "sf-05", feature: "bash 危险命令匹配", description: "BASH_DANGEROUS_PATTERNS 匹配 rm 递归删除（合并/分开/长选项/多空格）与 sudo 等危险命令", why: "命令注入防护", depth: "shallow", scenarios: ["safety-danger-pattern"] },
    { id: "sf-06", feature: "bash NOWAY 匹配", description: "BASH_NOWAY_PATTERNS 匹配 rm -rf /（根目录）与 sudo rm 等硬禁止命令，且不误杀 rm -rf /home/user", why: "系统破坏命令禁止", depth: "shallow", scenarios: ["safety-noway-pattern"] },
    { id: "sf-07", feature: "文件路径分级", description: "resolveFilePathLevel 按路径分级：私钥凭据一律 NOWAY、.env 与系统目录 DANGER、普通路径 SAFE，Windows 反斜杠先归一，缺失 path 参数不提级；FILE_DANGEROUS_PATTERNS 仍是两个等级（凭据级 NOWAY 与敏感级 DANGER）正则的按子集并集；该分级确实挂在注册过的生产工具上 —— pi-read 按调用参数里的 path 分级，pi-bash 在命令模式匹配之后按同一规则逐个路径 token 取更严者（`cat ~/.ssh/id_rsa` 升为 NOWAY，普通路径不被误提级）", why: "敏感文件泄露防护，且分级必须真正接在生产工具上而不只是被断言", depth: "shallow", scenarios: ["safety-file-pattern"] },
    { id: "sf-09", feature: "LLM 危险 Bash 调用实际拦截", description: "模型请求 rm -rf / 时，Bash 硬禁止策略在执行前拒绝执行；模型输出由 fake Provider 固定，工具与安全链路真实", why: "端到端安全验证", depth: "deep", scenarios: ["safety-dangerous-delete"] },
    { id: "sf-10", feature: "Pi 工具门禁 fail-closed", description: "Pi 原生工具门禁（Harness before_tool 复用同一语义）在 block 与抛错两种情况下都不执行工具，并留下带原因的 error 工具结果", why: "工具门禁必须 fail-closed，否则安全策略只是建议", depth: "deep", scenarios: ["safety-hook-errors"] },
    { id: "sf-11", feature: "MCP passthrough 终裁", description: "MCP 适配器的权限意见只能是 policy.permission.defaultDecision=passthrough；PermissionKernel 必须把它收敛为 allow、ask 或 deny，executor 不得看到 passthrough。发现侧把 MCP 工具声明为 DANGER（sf-21），因此默认安全模式下 passthrough 的收敛结果是 ask —— 重写本点场景要按 DANGER 选探针，NORMAL 在新裁决表下会先被标准决策放行", why: "发现远端工具不等于默认信任", depth: "deep", scenarios: ["permission-passthrough-final"] },
    { id: "sf-12", feature: "PermissionKernel deny-first", description: "不可放宽的 NOWAY 硬拒绝优先于工具策略里的 allow；工具侧 defaultDecision 与标准决策取交集：任一侧是 ask 就是 ask（工具声明的独立 ask 不被普通 allow 吞掉），标准决策的 ask 也不能被工具侧 allow 降级为放行，工具侧 deny 直接拒绝，工具返回表外意见按 deny 处理。新裁决表下**走到 ask 只剩两条路**：DANGER 在默认安全模式下，或工具自己声明 defaultDecision: 'ask'；「NORMAL 在助手模式下必为 ask」的旧路径已不存在，所以重写本点场景必须用 DANGER（或工具侧 ask）做 ask 探针", why: "权限组合必须 fail-closed，且 ask 的来源在统一裁决后已收窄，旧探针会落在永久 allow 的分支上", depth: "deep", scenarios: ["permission-deny-first"] },
    { id: "sf-13", feature: "确认身份与失效", description: "权限评估要求 sessionId、runGeneration、toolCallId 与当前代际；缺失、取消或旧代际一律拒绝", why: "旧确认不得授权新回合", depth: "deep", scenarios: ["permission-identity-invalid"] },
    { id: "sf-14", feature: "精确会话授权", description: "allow_session 仅复用相同 session、generation、tool、参数与策略指纹的未过期授权；策略指纹由工具策略（含策略版本与执行/投影/摘要维度；mode 维度已删）、本次解析的风险等级、安全模式与信任开关（后二者取回合冻结快照）共同决定，任何一项变化都不复用旧授权。策略版本已递增到 2（安全等级到裁决的映射语义变化，§8.5）：旧版本声明连同旧授权一起失效，授权表本身是模块级内存 Map、不落盘也不过进程", why: "一次确认不能扩大到其他输入、回合或已改变的策略", depth: "deep", scenarios: ["permission-session-grant"] },
    { id: "sf-15", feature: "取消确认", description: "已取消 signal 的确认立即按拒绝结算，不遗留 pending UI", why: "取消不能让旧确认继续授权", depth: "deep", scenarios: ["permission-aborted-confirm"] },
    { id: "sf-16", feature: "凭据路径的 Rust 终判", description: "经 IPC 直连 file_read 与 bash_exec：凭据路径（`.ssh` 目录组件、`.pem`/`.key` 后缀，`.sshnotes` 这类前缀不算）被拒绝 —— 文件入口返回 SENSITIVE_PATH 而不是 PATH_NOT_FOUND（词法判定先于 canonicalize，不存在的路径也一样；写入侧在归一化路径、canonicalize 后的祖先与叶子链接上各判一次），bash 入口返回 TOOL 且文案指明凭据路径（层 1 的 deny_credential_paths，与层 1 硬基线、层 2 的系统路径保护并列，调用方不可关闭）。bash 入口**不再接受 scope 与白名单入参**（决策 7：Rust 的 `BashPolicy`/`BashScope`/`enforce_whitelist`/`first_control_syntax` 已删，`enforce_bash_policy(command)` 只收命令本身），所以拒绝不可能来自白名单、策略强度或超时 —— 旧描述里「两种 scope 共用」的前提已不存在", why: "TS 分级副本可被绕过，凭据泄露的最终判定必须在 Rust 且不可关闭；入参面收窄让「调用方无法传弱」本身成为结论", depth: "deep", scenarios: ["safety-credential-paths"] },
    { id: "sf-17", feature: "私钥读取被拦", description: "模型请求 read .ssh/id_rsa 时工具不以 done 收场、不经确认通道放行（确认被批准也不能把它放行），会话条目里不出现 OpenSSH 私钥正文", why: "私钥只读一次就足以泄露，且泄露会持久化进会话文件", depth: "deep", scenarios: ["safety-credential-read-blocked"] },
    { id: "sf-18", feature: "凭据命令的子进程边界", description: "模型请求 bash 把私钥重定向到文件时工具不以 done 收场；安全基线在 spawn 之前拒绝（被拦回合的耗时远早于命令自然时长），重定向产物不存在 —— 子进程从未产生", why: "bash 是绕过文件工具读取凭据的另一条入口，拦截必须发生在执行之前", depth: "deep", scenarios: ["safety-credential-bash-blocked"] },
    { id: "sf-19", feature: "权限策略按回合冻结", description: "PermissionContext 带预检冻结的 policy：回合中改安全模式不改变本回合的裁决与 policyHash，从下一回合生效", why: "裁决与授权哈希必须来自同一份策略快照，否则同一次确认可能在策略变动后命中旧授权", depth: "deep", scenarios: ["memory-permission-freeze"] },
    { id: "sf-20", feature: "子代理授权的会话与代际绑定", description: "计划步骤子代理内的 allow_session 授权按父会话与父槽代际入账：运行内确认请求的身份与工具上下文读到的父会话/父代际逐字段一致，同参第二次命中 grant 不再确认；回合结束后 grant 随 invalidatePermissionScope(会话, 代际) 释放，同参同身份重评估回到 ask；切会话后同参 grant 同样不得命中，必须重新确认", why: "授权不绑定会话与代际会让用户在不知情的新会话里被放行，或让旧代际的授权在运行结束后继续生效", depth: "deep", scenarios: ["safety-subagent-grant-scope"] },
    { id: "sf-21", feature: "逐工具重定级", description: "决策 6 的「统一裁决表」与「逐工具重定级」是同一枚硬币：NORMAL 从「助手模式下必 ask」变成「一律 allow」之后，必须同时把隐私与远端能力的声明等级提上去 —— clipboard_read 与 agent_spawn 由 NORMAL 提为 DANGER，MCP 工具（发现侧 client.ts）声明为 DANGER，因此三者在默认安全模式下走 ask（just_do_it 下 allow）而不是被 NORMAL 静默放行；pi-bash 的白名单命令保持 NORMAL 并因此变成免确认（白名单只是免确认通道），app_open 与 clipboard_write 本来就是 DANGER、本次不变。注：本点钉的是注册表里读到的声明等级（可直接断言），实际确认动作由 sf-03 与 /skill、子代理的准入路径覆盖；caseId `safety-regraded-tools`（T20 新建）当前不存在于 `scenes/`，本点尚无场景覆盖", why: "「统一后 NORMAL 一律放行」本身是放宽，提级是它的唯一补偿；漏掉任一项都会让剪贴板读取、子代理或远端 MCP 调用从「每次都问」变成「从不问」", depth: "shallow", scenarios: ["safety-regraded-tools"] },
  ],
  // 20 = 每个覆盖点至少一条已归属场景（该模块 20 条必覆盖行为）；13 = 必须由 deep 场景证明的必覆盖行为数
  // （sf-03/09/10/11/12/13/14/15/16/17/18/19/20）。
  rules: { minScenarios: 20, minDeepScenarios: 13, requireBoundary: true, requireErrorPath: true },
}
