import type { ModuleContract } from "../types"

export const toolExecutionContract: ModuleContract = {
  module: "tool-execution",
  sourceFiles: [
    "src/services/engine/pi/runtime.ts",
    "src/services/engine/pi/harness-slot.ts",
    "src/services/tool/router.ts",
    "src/services/tool/policy.ts",
    "src/services/tool/execution-permit.ts",
    "src/services/tool/session-transcript.ts",
    "src/services/context/tool-output.ts",
    "src/services/tool/registry.ts",
    "src/services/tool/local/pi-tools.ts",
    "src/services/tool/pi/harness-adapter.ts",
    "src/services/tool/pi/harness-tool-adapter.ts",
    "src/services/tool/pi/tauri-execution-env.ts",
    "src/services/safety/checker.ts",
    "src/services/reply/generator.ts",
    "src/services/engine/pi/net-guard.ts",
    "src/services/engine/pi/model-gateway.ts",
    "src/services/skill/loader.ts",
    "src-tauri/src/commands/skill_cmd.rs",
    "src-tauri/src/commands/tool_permit.rs",
    "src/services/tool/mcp/manager.ts",
  ],
  generatedAt: "2026-09-21",
  sourceHash: "35b9a63b40f1867db655e1eb168dc6686bcf1f8e313e2f91b9469bad38289f15",
  coverage: [
    { id: "te-13", feature: "工具结果持久化与回读", description: "生产工具配对作为会话条目持久化，完整工具文本保留（L0只改请求视图），read_session_event 按条目 id 分页回读并限定当前 session", why: "短请求不能以丢失工具证据为代价", depth: "deep", scenarios: ["tool-transcript-recovery"] },
    { id: "te-08", feature: "真 LLM 多工具调用", description: "真实 LLM 对话中先后调用多个工具", why: "端到端工具链验证", depth: "deep", scenarios: ["tool-system-info"] },
    { id: "te-09", feature: "Provider 网络边界", description: "Provider 固定用户配置的 origin，拒绝 host/scheme/port 漂移并禁止重定向携带认证；显式 localhost/provider 可用，响应按流限额", why: "避免网络策略绕过和内存失控", depth: "shallow", scenarios: ["tool-provider-network-boundary"] },
    { id: "te-10", feature: "工具取消错误码", description: "已取消的工具调用不进入 handler 且返回稳定错误码", why: "取消必须可观测且不可产生副作用", depth: "shallow", scenarios: ["tool-cancelled"] },
    { id: "te-11", feature: "Skill 元数据渐进加载", description: "catalog 只保留有界 frontmatter 元数据，正文不进缓存或 prompt；pet/assistant 按 invocationPolicy 筛选", why: "启动和首回合不能加载全部 Skill 正文，同时轻量模式只暴露明确声明的能力", depth: "deep", scenarios: ["tool-skill-metadata-progressive"] },
    { id: "te-12", feature: "Skill catalog 失效", description: "保存覆盖和删除 Skill 后，catalog 重新读取元数据真相源，不保留旧描述或已删除条目", why: "metadata cache 有界也必须随版本变化失效，避免向模型暴露不存在的能力", depth: "shallow", scenarios: ["tool-skill-catalog-invalidation"] },
    { id: "te-14", feature: "MCP 配置字段保留", description: "编辑内置 MCP 的常规字段时保留 includeTools/excludeTools，避免工具暴露范围静默扩大", why: "过滤规则是能力边界，设置页只编辑 args/env 不能抹掉源配置", depth: "shallow", scenarios: ["tool-mcp-config-preserve"] },
    { id: "te-15", feature: "工具策略门禁", description: "defineTool 与注册入口对完整策略统一校验并冻结：缺 policy、parallel 搭配非只读效果、exclusive_effect/delegate 非串行、未知策略版本、非法权限意见都报错，被拒绝的声明不进入注册表", why: "缺策略必须视为注册错误，不能缺省成可并行、可重放或某个默认权限", depth: "deep", scenarios: ["tool-policy-registration-gate"] },
    { id: "te-16", feature: "纯读并行、效果互斥与借用者生命周期", description: "shared_read 按 Rust 应用级许可的有界共享额度并发（两个只读真的重叠），共享读上限由 `ai.loop.maxParallelTools` 下发（范围 1–8：上限 1 只放一个读、提高上限唤醒排队读、越界下发被拒绝且不改变生效值、降低上限不撤销在飞许可），exclusive_effect 与进行中的读写互斥：等待发生在许可队列（queued 可观测）、独占期间开不出新读、读不插队到排队中的独占之前、取消排队中的独占会重新放行后面的读、执行结束才释放额度且没有泄漏；借用者身份 = 窗口 + 页面实例，新实例上线按「旧借用者已经不存在」一次性回收其额度与排队项（回收数量可观测），同一借用者重复上线是空操作，在飞的独占效果不被回收放开；释放与取消同样绑定借用者：其它窗口/页面即使拿到 requestId 也不能释放在飞额度或取消他人的排队项", why: "并行不能牺牲互斥：写类与其他执行必须串行，等待可取消且不让读饿死写，额度必须归还干净，上限变更不能留下越界或未生效的额度语义；页面重新加载（热重载）不再让借出的额度永久卡住后续工具，而回收不能靠时间放开仍在运行的效果", depth: "deep", scenarios: ["tool-execution-permit"] },
    { id: "te-17", feature: "策略驱动的请求投影", description: "resultProjection=preserve 的工具结果原样进入请求（不被 L0 二次缩短），reference 的被缩短并标注 eventId 回读地址；两种情况下会话条目存档都保持全文", why: "分页读取不能被反复压缩，缩短只能改请求视图而不能改存档", depth: "deep", scenarios: ["tool-result-projection"] },
    { id: "te-18", feature: "bash 取消与 spawn 的竞态", description: "取消在子进程 spawn 之前到达不再静默丢失：登记先于 spawn，命中槽的取消立案后由 spawn 后的回填点立即终止（返回稳定码 CANCELLED），未命中的取消返回 false 并留 debug 记录而不是静默成功；被取消的运行收口远早于命令自然时长与兜底超时，不留副作用，也不把额度留在占用态", why: "取消丢失会让子进程独自跑到 120s 超时：独占额度不归还、后续工具全部排队，而调用方以为已经停止", depth: "deep", scenarios: ["tool-cancel-before-spawn"] },
  ],
  rules: { minScenarios: 1, minDeepScenarios: 1, requireBoundary: true, requireErrorPath: true },
}
