import type { ModuleContract } from "../types"

export const toolExecutionContract: ModuleContract = {
  module: "tool-execution",
  sourceFiles: [
    "src/services/engine/pi/runtime.ts",
    "src/services/engine/pi/harness-slot.ts",
    "src/services/tool/router.ts",
    "src/services/tool/policy.ts",
    "src/services/tool/execution-permit.ts",
    "src/services/tool/session-transcript.ts",
    "src/services/context/tool-output.ts",
    "src/services/tool/registry.ts",
    "src/services/tool/local/pi-tools.ts",
    "src/services/tool/pi/harness-adapter.ts",
    "src/services/tool/pi/harness-tool-adapter.ts",
    "src/services/tool/pi/tauri-execution-env.ts",
    "src/services/safety/checker.ts",
    "src/services/reply/generator.ts",
    "src/services/engine/pi/net-guard.ts",
    "src/services/engine/pi/model-gateway.ts",
    "src/services/skill/loader.ts",
    "src-tauri/src/commands/skill_cmd.rs",
    "src-tauri/src/commands/tool_permit.rs",
    "src-tauri/src/commands/tool_exec.rs",
    "src/services/tool/mcp/manager.ts",
    "src/services/tool/mcp/client.ts",
    "src/services/tool/types.ts",
  ],
  generatedAt: "2026-09-24",
  sourceHash: "993efd3908976f3e8b303acead851acd9bec5dde3a15b4404073f7d8d7f4fdfe",
  coverage: [
    { id: "te-13", feature: "工具结果持久化与回读", description: "生产工具配对作为会话条目持久化，完整工具文本保留（L0只改请求视图，Router 无 L1 内联截断），read_session_event 按条目 id 分页回读并限定当前 session（reader 是槽上的 readToolResult，工具只认 entryId）；超上限边界上条目仍为全文、请求视图带真 eventId 地址、bash 截断带 spill 回读路径（实际生效上限由 Rust 回传）。注：MCP 结果限幅（`mcp/client.ts`：超过 MAX_MCP_RESULT_CHARS 截断，正文里如实标记「不保留全文」，不写假 eventId）未由本点的两个场景断言 —— 它们覆盖的是会话条目全文 / 请求视图缩短 / bash spill 三条路径", why: "短请求不能以丢失工具证据为代价", depth: "deep", scenarios: ["tool-transcript-recovery", "tool-archive-beyond-inline-limit"] },
    { id: "te-08", feature: "真 LLM 多工具调用", description: "真实 LLM 对话中先后调用多个工具", why: "端到端工具链验证", depth: "deep", scenarios: ["tool-system-info"] },
    { id: "te-09", feature: "Provider 网络边界", description: "Provider 固定用户配置的 origin，拒绝 host/scheme/port 漂移并禁止重定向携带认证；显式 localhost/provider 可用，响应按流限额", why: "避免网络策略绕过和内存失控", depth: "shallow", scenarios: ["tool-provider-network-boundary"] },
    { id: "te-10", feature: "工具取消错误码", description: "已取消的工具调用不进入 handler 且返回稳定错误码；超时与取消的判定顺序唯一（定时器置位记 timeout、外部 signal 记 cancelled，不靠错误文案），一次调用只有一条审计", why: "取消必须可观测且不可产生副作用，取消与超时不得互换", depth: "shallow", scenarios: ["tool-cancelled", "tool-timeout-outcome-single"] },
    { id: "te-11", feature: "Skill 元数据渐进加载", description: "catalog 只保留有界 frontmatter 元数据，正文不进缓存或 prompt；pet/assistant 按 invocationPolicy 筛选", why: "启动和首回合不能加载全部 Skill 正文，同时轻量模式只暴露明确声明的能力", depth: "deep", scenarios: ["tool-skill-metadata-progressive"] },
    { id: "te-12", feature: "Skill catalog 失效", description: "保存覆盖和删除 Skill 后，catalog 重新读取元数据真相源，不保留旧描述或已删除条目", why: "metadata cache 有界也必须随版本变化失效，避免向模型暴露不存在的能力", depth: "shallow", scenarios: ["tool-skill-catalog-invalidation"] },
    { id: "te-14", feature: "MCP 配置字段保留", description: "编辑内置 MCP 的常规字段时保留 includeTools/excludeTools，避免工具暴露范围静默扩大", why: "过滤规则是能力边界，设置页只编辑 args/env 不能抹掉源配置", depth: "shallow", scenarios: ["tool-mcp-config-preserve"] },
    { id: "te-15", feature: "工具策略门禁", description: "defineTool 与注册入口对完整策略统一校验并冻结：缺 policy、`shared_read` 搭配非只读效果、未知策略版本、非法权限意见都报错（并发语义只由 isolation/effect 表达，`execution.mode` 与 `permission.check` 已无实现），被拒绝的声明不进入注册表；注册表按对象身份入库不克隆，`getToolByName` 返回同一份冻结定义；执行函数不在 ToolDef 公开字段里（经 defineTool 进入模块内 WeakMap），未经 defineTool 构造的定义在注册时被拒。注：同一次校验里的风险声明校验（`safetyLevel` 必须四级之一、`lightweightPolicy` 只允许 confirm/deny，旧 `allow` 已无实现）未由本点场景断言", why: "缺策略必须视为注册错误，不能缺省成可并行、可重放或某个默认权限；执行体只能来自唯一构造入口", depth: "deep", scenarios: ["tool-policy-registration-gate", "tool-define-only-construction"] },
    { id: "te-16", feature: "纯读并行、效果互斥与借用者生命周期", description: "shared_read 按 Rust 应用级许可的有界共享额度并发（两个只读真的重叠），共享读上限由 `ai.loop.maxParallelTools` 下发（范围 1–8：上限 1 只放一个读、提高上限唤醒排队读、越界下发被拒绝且不改变生效值、降低上限不撤销在飞许可），exclusive_effect 与进行中的读写互斥：等待发生在许可队列（queued 可观测）、独占期间开不出新读、读不插队到排队中的独占之前、取消排队中的独占会重新放行后面的读、执行结束才释放额度且没有泄漏；借用者身份 = 窗口 + 页面实例，新实例上线按「旧借用者已经不存在」一次性回收其额度与排队项（回收数量可观测），同一借用者重复上线是空操作，在飞的独占效果不被回收放开；释放与取消同样绑定借用者：其它窗口/页面即使拿到 requestId 也不能释放在飞额度或取消他人的排队项；释放是一条 IPC，失败时额度会留在所有者手里（后续独占效果一直排队而工具结果看起来成功），因此释放失败的 requestId 入队补偿、在下一次 run 开始前重放归还（requestId 是确定量，Rust 对未知 id 返回 Ok，重放幂等），借用者的上线声明失败同样记欠账并在同一时点重试", why: "并行不能牺牲互斥：写类与其他执行必须串行，等待可取消且不让读饿死写，额度必须归还干净，上限变更不能留下越界或未生效的额度语义；页面重新加载（热重载）不再让借出的额度永久卡住后续工具，而回收不能靠时间放开仍在运行的效果；释放失败只留一行日志同样会把额度永久卡死后续独占效果", depth: "deep", scenarios: ["tool-execution-permit", "tool-permit-release-compensation"] },
    { id: "te-17", feature: "策略驱动的请求投影", description: "resultProjection=preserve 的工具结果原样进入请求（不被 L0 二次缩短），reference 的被缩短并标注 eventId 回读地址；两种情况下会话条目存档都保持全文", why: "分页读取不能被反复压缩，缩短只能改请求视图而不能改存档", depth: "deep", scenarios: ["tool-result-projection"] },
    { id: "te-18", feature: "bash 取消与 spawn 的竞态", description: "取消在子进程 spawn 之前到达不再静默丢失：登记先于 spawn（登记前先过策略与 execution_id 校验），命中槽的取消立案后由 spawn 后的回填点立即终止（返回稳定码 CANCELLED，或非零退出），未命中的取消返回 false 并留 debug 记录而不是静默成功；被取消的运行收口远早于命令自然时长与兜底超时（正对照证明同形态命令不加取消会跑完并留下探针）、不留重定向产物，也不把额度留在占用态（shared/exclusive/queued 全回空闲）；「取消正好落在登记与 spawn 之间」的微秒级窗口无法从 JS 侧确定性复现，由 Rust 单测直接钉住（`bash_cancel_lands_before_spawn` / `bash_cancel_unknown_id_returns_false` / `bash_cancel_latches_slot_without_child`）；本机 macOS 只验证 unix 分支（`cmd /C` 选择与 Windows 的进程终止行为依赖 Windows CI）", why: "取消丢失会让子进程独自跑到 120s 超时：独占额度不归还、后续工具全部排队，而调用方以为已经停止", depth: "deep", scenarios: ["tool-cancel-before-spawn"] },
  ],
  // 11 = 每个覆盖点至少一条已归属场景（该模块 11 条必覆盖行为）；7 = 必须由 deep 场景证明的必覆盖行为数
  // （te-08/te-11/te-13/te-15/te-16/te-17/te-18）。当前 15 条场景 / 9 条 deep，门槛留余量而不虚报。
  rules: { minScenarios: 11, minDeepScenarios: 7, requireBoundary: true, requireErrorPath: true },
}
