import type { ModuleContract } from "../types"

export const variablePoolContract: ModuleContract = {
  module: "variable-pool",
  sourceFiles: ["src/services/engine/pi/runtime.ts", "src/services/personality/variable-pool.ts", "src/services/personality/types.ts", "src/services/personality/stages-file.ts", "src/services/reply/generator.ts"],
  generatedAt: "2026-09-23",
  sourceHash: "e73b600a1c87931e172b838d75b901c2a1b07b57ce208837728d6864268ce349",
  coverage: [
    { id: "vp-01", feature: "系统变量计算", description: "computeSystemVariables 计算6个系统变量", why: "Prompt 注入基础", depth: "shallow", scenarios: ["variable-system-vars"] },
    { id: "vp-02", feature: "变量池初始化", description: "initVariablePool 从Card variableDefs初始化", why: "Card切换和重启时正确构建", depth: "deep", scenarios: ["variable-pool-init"] },
    { id: "vp-03", feature: "变量池刷新", description: "refreshVariablePool 重新计算系统变量", why: "每轮对话前刷新", depth: "deep", scenarios: ["variable-pool-refresh"] },
    { id: "vp-04", feature: "RUNTIME_DATA 写入变量池", description: "真实模型按提示发出 RUNTIME_DATA 后，池里的值与请求一致（字符串按 coerceValue 规则去引号比较）且 updatedBy=llm；模型未请求写入的那一轮放过，但整场至少要有一次，否则视为链路未被验证", why: "回复生成器拥有变量写入边界；断言模型自发每轮都写属于模型行为而非引擎契约", depth: "deep", scenarios: ["variable-affection-praise"] },
    { id: "vp-05", feature: "batchWriteVars 拒绝未注册变量", description: "写入未在 variableDefs 中定义的变量被拒绝", why: "防止 LLM 写入未定义变量", depth: "shallow", scenarios: ["variable-pool-unregistered"] },
    { id: "vp-06", feature: "batchWriteVars 类型/范围约束", description: "number/string/boolean 类型校验 + number min/max + string enum，非法值拒绝", why: "防护 LLM 幻觉", depth: "shallow", scenarios: ["variable-boundary-reject"] },
    { id: "vp-07", feature: "batchWriteVars updateBy=system 只读", description: "updateBy 不是 llm 的 card 变量无法通过 batchWriteVars 写入", why: "保护系统变量", depth: "shallow", scenarios: ["variable-pool-system-readonly"] },
    { id: "vp-08", feature: "RUNTIME_DATA 变量写入端到端", description: "LLM 回复含 RUNTIME_DATA 变量行 → 引擎解析 → batchWriteVars → pool 更新", why: "核心写入闭环", depth: "deep", scenarios: ["variable-runtime-data-write"] },
    { id: "vp-09", feature: "Reset=never策略", description: "reset: never 的 card 变量不参与任何重置：换日与新会话两个触发条件同时成立也纹丝不动；策略由 applyResetPolicies(now, sessionKey) 每轮应用", why: "亲密度等长期变量不能被日切或换会话顺手清掉", depth: "deep", scenarios: ["variable-reset-never"] },
    { id: "vp-10", feature: "Reset=daily策略", description: "reset: daily 按本地日期键重置且幂等：游标缺省（首次激活/升级前数据）视为陈旧、重置一次并推进游标，同一日期键重复调用不再重置；daily 只影响自己，不顺手重置 session 变量", why: "每日变量正确重置，且判定必须幂等", depth: "deep", scenarios: ["variable-reset-daily"] },
    { id: "vp-11", feature: "Reset=session策略", description: "reset: session 只按传入的持久化 sessionKey 判定：键为 null 不做判定（不能凭空认定新会话），与已应用键不同才重置一次，同一键重复调用幂等", why: "会话级变量刷新不能退化成每轮清空", depth: "deep", scenarios: ["variable-reset-session"] },
    { id: "vp-12", feature: "交互变量更新", description: "updateInteractionVar写入interaction变量", why: "系统行为反馈", depth: "deep", scenarios: ["variable-interaction-update"] },
    { id: "vp-13", feature: "持久化保存", description: "savePoolToDisk/savePoolToDiskStrict 把变量区写进 stages/{cardId}.json 的 variables 段（经 updateStagesFile 的段级合并，不再单独写 vars.json）：card 与 interaction 变量、两个重置游标同一次写盘；async 路径失败 log.warn 不抛，strict 路径失败抛出交给事务回滚", why: "重启不丢变量，且写盘不得与阶段文案互相覆写", depth: "deep", scenarios: ["variable-pool-save"] },
    { id: "vp-14", feature: "持久化恢复", description: "loadCardVars 从 stages/{cardId}.json 的 variables 段恢复 card/interaction 变量与两个重置游标；文件不存在或变量区缺失/schemaVersion 不合法时返回 null（调用方按 Card 初始值重建）", why: "重启恢复，且「变量区缺失」必须可被识别而不是静默用空池顶替", depth: "deep", scenarios: ["variable-pool-load"] },
    { id: "vp-15", feature: "formatPoolForPrompt", description: "四类变量格式化为LLM可读文本", why: "LLM prompt变量注入", depth: "shallow", scenarios: ["variable-pool-prompt"] },
    { id: "vp-16", feature: "snapshot/restore变量池", description: "保存恢复运行时状态", why: "重试快照回滚", depth: "shallow", scenarios: ["variable-pool-snapshot"] },
    { id: "vp-17", feature: "变量池销毁", description: "destroyPool清空所有变量", why: "场景间状态隔离", depth: "deep", scenarios: ["variable-pool-destroy"] },
    { id: "vp-18", feature: "持久化恢复非法值回退", description: "持久化值超出范围回退到initial", why: "防护磁盘数据损坏", depth: "shallow", scenarios: ["variable-pool-invalid-restore"] },
    { id: "vp-19", feature: "阶段文案与变量区共存", description: "stages 段与 variables 段共享 stages/{cardId}.json：变量（含 interaction）与两个重置游标先落盘后，阶段文案写入仍原样保留变量区；变量池再写一次，stages 段同样原样保留（两个唯一生产者经段级合并互不抹除）", why: "改动前三个写入者各自整文件覆写会静默抹掉变量区，现场要等下次激活 Card 才可见 —— VAR-01 的防回归断言", depth: "deep", scenarios: ["variable-pool-stages-coexist"] },
    { id: "vp-20", feature: "daily 游标跨重启", description: "daily 重置游标随 variables 段落盘：destroy → 重新 init（透传磁盘游标）后同一天不重置、跨日重置一次并把新游标落盘；游标缺失时视为陈旧重置一次；不存在的 Card 由 loadCardVars 返回 null 交给调用方重建", why: "游标只写不读会让 daily 变量每次重启都重新判定一次，跨天的语义整个失效", depth: "deep", scenarios: ["variable-pool-daily-cursor-restart"] },
    { id: "vp-21", feature: "session 游标按持久化键判定", description: "session 重置只按持久化的 sessionKey 判定：键为 null 不做判定、同一键（含跨重启）幂等、换键重置一次并把新键落盘；旧数据缺会话游标时不产生任何重置", why: "没有持久化键时凭空认定「新会话」会让变量被反复清空，键不落盘则重启后判定失去依据", depth: "deep", scenarios: ["variable-pool-session-cursor"] },
  ],
  rules: { minScenarios: 15, minDeepScenarios: 9, requireBoundary: true, requireErrorPath: true },
}
