import type { ModuleContract } from "../types"

export const variablePoolContract: ModuleContract = {
  module: "variable-pool",
  sourceFiles: ["src/services/personality/variable-pool.ts", "src/services/personality/types.ts"],
  generatedAt: "2026-07-24T00:00:00Z",
  sourceHash: "",
  coverage: [
    { id: "vp-01", feature: "系统变量计算", description: "computeSystemVariables 计算6个系统变量", why: "When规则和prompt注入基础", depth: "shallow", scenarios: [] },
    { id: "vp-02", feature: "变量池初始化", description: "initVariablePool 从Card variableDefs初始化", why: "Card切换和重启时正确构建", depth: "deep", scenarios: [] },
    { id: "vp-03", feature: "变量池刷新", description: "refreshVariablePool 重新计算系统变量", why: "每轮对话前刷新", depth: "deep", scenarios: [] },
    { id: "vp-04", feature: "Card变量 LLM写入", description: "用户夸奖/批评 → LLM调var_write更新变量", why: "核心更新闭环", depth: "deep", scenarios: ["亲密度提升"] },
    { id: "vp-05", feature: "varWrite拒绝:越界值", description: "number变量超出min/max被拒绝", why: "防护LLM幻觉", depth: "shallow", scenarios: ["越界拒绝"] },
    { id: "vp-06", feature: "varWrite拒绝:枚举不匹配", description: "string变量不在enum列表被拒绝", why: "防护LLM幻觉", depth: "shallow", scenarios: [] },
    { id: "vp-07", feature: "varWrite拒绝:类型不匹配", description: "boolean变量写非true/false被拒绝", why: "防护LLM幻觉", depth: "shallow", scenarios: [] },
    { id: "vp-08", feature: "varWrite拒绝:系统变量只读", description: "写system变量被拒绝", why: "保护系统计算变量", depth: "shallow", scenarios: [] },
    { id: "vp-09", feature: "varDelete重置到初始值", description: "varDelete将变量恢复为initial", why: "变量生命周期管理", depth: "shallow", scenarios: [] },
    { id: "vp-10", feature: "varRead/varList读取", description: "读取单个/全部变量", why: "LLM工具读取变量", depth: "shallow", scenarios: [] },
    { id: "vp-11", feature: "Reset=never策略", description: "永不重置的持久变量", why: "亲密度等不能丢", depth: "deep", scenarios: [] },
    { id: "vp-12", feature: "Reset=daily策略", description: "日期变更时重置", why: "每日变量正确重置", depth: "deep", scenarios: [] },
    { id: "vp-13", feature: "Reset=session策略", description: "新会话时重置", why: "会话级变量刷新", depth: "deep", scenarios: [] },
    { id: "vp-14", feature: "交互变量更新", description: "updateInteractionVar写入interaction变量", why: "系统行为反馈", depth: "deep", scenarios: [] },
    { id: "vp-15", feature: "持久化保存", description: "savePoolToDisk写入stages/{cardId}.json", why: "重启不丢变量", depth: "deep", scenarios: [] },
    { id: "vp-16", feature: "持久化恢复", description: "loadCardVars从磁盘恢复变量", why: "重启恢复", depth: "deep", scenarios: [] },
    { id: "vp-17", feature: "formatPoolForPrompt", description: "四类变量格式化为LLM可读文本", why: "LLM prompt变量注入", depth: "shallow", scenarios: [] },
    { id: "vp-18", feature: "snapshot/restore变量池", description: "保存恢复运行时状态", why: "重试快照回滚", depth: "shallow", scenarios: [] },
    { id: "vp-19", feature: "变量池销毁", description: "destroyPool清空所有变量", why: "场景间状态隔离", depth: "deep", scenarios: [] },
    { id: "vp-20", feature: "持久化恢复非法值回退", description: "持久化值超出范围回退到initial", why: "防护磁盘数据损坏", depth: "shallow", scenarios: [] },
  ],
  rules: { minScenarios: 16, minDeepScenarios: 9, requireBoundary: true, requireErrorPath: true },
}
