// Generated by scripts/generate-memory-protocol.mjs. Do not edit.

export type MemoryScope = "user" | "card" | "session"

export type MemoryKind = "fact" | "preference" | "episode" | "working"

export type MemoryStatus = "active" | "superseded" | "expired" | "forgotten"

export type CandidateStatus = "pending_review" | "accepted" | "rejected" | "stale"

export interface MemorySource {
  sourceId: string
  sessionId: string
  entryId: string
  eventId?: string
  seq: number
  contentHash: string
  evidence?: string
  eligibleForMemory: boolean
  taint: "trusted_user" | "derived" | "untrusted" | "system"
  origin: "user" | "assistant" | "tool" | "system" | "import"
  observedAt: number
}

export interface MemoryDraft {
  content: string
  summary: string
  kind: MemoryKind
  scope: MemoryScope
  scopeId?: string
  aliases: Array<string>
  pinned: boolean
  importance: number
  confidence: number
  observedAt?: number
  validFrom?: number | null
  validTo?: number | null
  expiresAt?: number | null
  supersedesId?: string | null
  sourceIds: Array<string>
}

export interface MemoryItem {
  id: string
  version: number
  status: MemoryStatus
  draft: MemoryDraft
  createdAt: number
  updatedAt: number
}

export interface MemoryCandidate {
  id: string
  jobId: string
  status: CandidateStatus
  draft: MemoryDraft
  baseRevision: number
  payloadHash: string
  createdAt: number
  reason?: string
}

export interface MemoryJob {
  id: string
  phase: "light" | "review" | "publish"
  status: "queued" | "running" | "paused" | "cancelled" | "completed" | "failed"
  revision: number
  forgetEpoch: number
  leaseOwner?: string | null
  leaseUntil?: number | null
  cursor?: string
  processed?: number
  createdAt: number
  updatedAt: number
  error?: string
}

export interface MemoryCandidateDraft {
  id?: string
  draft: MemoryDraft
  payloadHash: string
  baseRevision?: number
  reason?: string
}

export type MemoryCommand = "memory_status" | "memory_list" | "memory_detail" | "memory_register_sources" | "memory_query" | "memory_get_items" | "memory_apply_change" | "memory_job_start" | "memory_job_checkpoint" | "memory_job_cancel" | "memory_job_resume" | "memory_job_sources" | "memory_candidates_add" | "memory_review_batch" | "memory_publish_batch" | "memory_export" | "memory_backup" | "memory_rebuild" | "memory_restore"
