// Generated by scripts/generate-memory-protocol.mjs. Do not edit.

export interface ConversationIndexEntry {
  entryId: string
  eventId: string | null
  seq: number
  chunk: number
  role: "user" | "assistant"
  text: string
  timestamp: number
  anchorEntryId?: string | null
  anchorEventId?: string | null
}

export interface ConversationIndexBatch {
  id: string
  offset: number
  complete: boolean
}

export interface ConversationClearFence {
  sessionId: string
  maxSeq: number
}

export interface ConversationSearchEntry {
  entryId: string
  eventId: string | null
  seq: number
  chunk: number
  role: "user" | "assistant"
  text: string
  timestamp: number
  anchorEntryId?: string | null
  anchorEventId?: string | null
  sessionId: string
  score: number
}

export interface ConversationIndexStatus {
  stagedSessionIds: Array<string>
  sessions: Array<{ "sessionId": string; "fingerprint": string }>
  revision: number
  forgetEpoch: number
}

export interface ConversationSearchResult {
  revision: number
  memoryRevision: number
  forgetEpoch: number
  entries: Array<ConversationSearchEntry>
}

export type MemoryScope = "user" | "card" | "session"

export type MemoryKind = "fact" | "preference" | "episode" | "working"

export type MemoryOrigin = "user" | "derived_behavior"

export type MemoryStatus = "active" | "superseded" | "expired" | "forgotten"

export type WorkingState = "open" | "completed" | "cancelled"

export type MemoryChangeActor = "current_input" | "user_ui" | "internal"

export type ProactiveAttemptKind = "planning" | "expression"

export type ProactiveAttemptStatus = "reserved" | "generating" | "committed" | "failed" | "unresolved" | "skipped"

export type ProactiveDecisionKind = "decline" | "speak_now" | "schedule" | "set_presence"

export type TemporalAnchor = { "precision": "day"; "localDate": string; "timezone": string } | { "precision": "minute"; "instant": number; "timezone": string }

export interface ProactiveRecurrence {
  frequency: "daily" | "weekly" | "monthly" | "yearly"
  localTime: string
  timezone: string
  weekdays?: Array<number>
  dayOfMonth?: number
  month?: number
}

export interface ProactiveSourceRef {
  kind: "memory" | "user_entry" | "behavior" | "variable" | "calendar" | "task" | "card"
  id: string
  version: number
  revision: number
  scope: MemoryScope
  scopeId: string | null
  fingerprint: string
  validUntil: number | null
}

export interface ProactiveOwner {
  sessionId: string
  cardId: string
  cardHash: string
  runGeneration: number
}

export interface ProactiveTask {
  id: string
  version: number
  scope: MemoryScope
  scopeId: string | null
  sourceRefs: Array<ProactiveSourceRef>
  intent: Record<string, unknown>
  eventAt: TemporalAnchor | null
  dueAt: TemporalAnchor | null
  nextCheckinAt: number | null
  validUntil: number | null
  timezone: string
  recurrence: ProactiveRecurrence | null
  state: "active" | "completed" | "cancelled" | "invalidated"
  createdAt: number
  updatedAt: number
}

export interface ProactiveTaskDraft {
  id: string
  scope: MemoryScope
  scopeId: string | null
  sourceRefs: Array<ProactiveSourceRef>
  intent: Record<string, unknown>
  eventAt: TemporalAnchor | null
  dueAt: TemporalAnchor | null
  nextCheckinAt: number | null
  validUntil: number | null
  timezone: string
  recurrence: ProactiveRecurrence | null
}

export interface ProactiveOpportunity {
  id: string
  ruleId: string
  sourceRefs: Array<ProactiveSourceRef>
  owner: ProactiveOwner
  intentKey: string
  validFrom: number
  validUntil: number
  priority: number
  fingerprint: string
}

export interface ProactiveBudget {
  localDate: string
  planningAttempts: number
  expressionAttempts: number
  successfulMessages: number
  reservedTokens: number
  usedTokens: number
  unknownTokens: number
  observationAttempts: number
  topicAttempts: number
  nextSuccessAfter: number | null
  dailySuccessLimit: number
  cooldownUntil: number | null
}

export interface ProactiveControl {
  muteUntil: number | null
  revision: number
}

export interface ProactiveLimits {
  wakeMinMs: number
  wakeMaxMs: number
  dailySuccess: number
  dailyExpressionAttempts: number
  dailyPlanningAttempts: number
  dailyAuxiliaryAttempts: number
  minSuccessIntervalMs: number
  successIntervalSpreadMs: number
  dailyTokens: number
  staySeconds: number
  settleMs: number
  cooldownMs: number
  samePageCooldownMs: number
}

export interface ProactiveAuxiliaryBudgetReserveRequest {
  reservationId: string
  requestId: string
  kind: "observation" | "topic"
  localDate: string
  reservedTokens: number
  dailyLimit: number
  now: number
}

export interface ProactiveAuxiliaryBudgetReserveResponse {
  reserved: boolean
  reason: string | null
}

export interface ProactiveAuxiliaryBudgetSettleRequest {
  reservationId: string
  localDate: string
  status: "committed" | "failed" | "unresolved"
  usage: Record<string, unknown> | null
  now: number
}

export interface ProactiveAuxiliaryBudgetSettleResponse {
  status: "committed" | "failed" | "unresolved"
}

export interface ProactiveScanRequest {
  owner: ProactiveOwner
  now: number
  localDate: string
  unansweredThresholdDate?: string | null
  unansweredClearedDate?: string | null
  cursor?: string
  targetCursor?: string
  limit?: number
  sourceRefs?: Array<ProactiveSourceRef>
}

export interface ProactiveMemoryTarget {
  id: string
  version: number
  scope: MemoryScope
  scopeId: string | null
  eventAt: TemporalAnchor | null
  dueAt: TemporalAnchor | null
  workingState: WorkingState | null
  kind: MemoryKind
  aliases: Array<string>
  sourceIds: Array<string>
  updatedAt: number
}

export interface ProactiveScanResponse {
  tasks: Array<ProactiveTask>
  memoryTargets: Array<ProactiveMemoryTarget>
  evaluatedFingerprints: Array<string>
  unresolvedAttempts: Array<ProactiveAttempt>
  usedTopicKeys: Array<string>
  control: ProactiveControl
  budget: ProactiveBudget
  sourceRevision: number
  hasMore: boolean
  nextCursor: string | null
  targetHasMore: boolean
  nextTargetCursor: string | null
}

export interface ProactiveQueryRequest {
  owner: ProactiveOwner
  targets?: Array<Record<string, unknown>>
  attemptIds?: Array<string>
  sessionId?: string
  recentDelivered?: boolean
  limit: number
  receiptLookup?: { "attemptId": string; "assistantEntryId": string }
}

export interface ProactiveAttempt {
  attemptId: string
  status: ProactiveAttemptStatus
  sessionId: string
  assistantEntryId: string | null
  requestId: string
  owner: ProactiveOwner
  sourceRefs: Array<ProactiveSourceRef>
  usage: Record<string, unknown> | null
  sourceFingerprint: string
  localDate: string
  updatedAt: number
  decision: ProactiveDecision | null
}

export interface ProactiveQueryResponse {
  tasks: Array<ProactiveTask>
  attempts: Array<ProactiveAttempt>
  revision: number
  receipt?: { "committed": boolean }
}

export interface ProactiveChangeRequest {
  operationId: string
  baseRevision: number
  action: "create" | "reschedule" | "snooze" | "complete" | "cancel" | "control"
  owner: ProactiveOwner
  trustedUserEventId?: string
  taskId?: string
  expectedVersion?: number
  sourceRefs?: Array<ProactiveSourceRef>
  taskPatch?: Record<string, unknown>
  controlPatch?: Record<string, unknown>
}

export interface ProactiveChangeResponse {
  revision: number
  task: ProactiveTask | null
}

export interface ProactiveClaimRequest {
  attemptId: string
  requestId: string
  kind: ProactiveAttemptKind
  owner: ProactiveOwner
  sourceRefs: Array<ProactiveSourceRef>
  sourceFingerprint: string
  sourceRevision: number
  controlRevision: number
  occurrenceIds: Array<string>
  now: number
  localDate: string
  reservedTokens: number
  ruleId: string
  unansweredThresholdDate?: string | null
  unansweredClearedDate?: string | null
}

export interface ProactiveClaimResponse {
  claimed: boolean
  reason: string | null
  leaseUntil: number | null
  revision: number
}

export interface ProactiveValidateRequest {
  attemptId: string
  owner: ProactiveOwner
  now: number
}

export interface ProactiveValidateResponse {
  valid: boolean
  reason: string | null
  sourceRevision: number
  controlRevision: number
}

export interface ProactiveSettleRequest {
  attemptId: string
  owner: ProactiveOwner
  sourceFingerprint: string
  localDate: string
  status: "committed" | "failed" | "skipped" | "unresolved"
  decision: ProactiveDecision | null
  assistantEntryId?: string
  usage: Record<string, unknown> | null
  errorCode?: string
  summary?: string
}

export interface ProactiveDecision {
  kind: ProactiveDecisionKind
  ruleId?: string
  opportunityFingerprints: Array<string>
  topicKey: string | null
  slot: string | null
  validUntil: number | null
  taskDrafts?: Array<ProactiveTaskDraft>
  presence?: Record<string, unknown> | null
}

export interface ProactiveReconcileRequest {
  attemptId: string
  owner: ProactiveOwner
  sourceFingerprint: string
  localDate: string
  assistantEntryId?: string
  committed: boolean
  usage: Record<string, unknown> | null
}

export interface ProactiveControlRequest {
  operationId: string
  baseRevision: number
  owner: ProactiveOwner
  patch?: { "muteUntil"?: number | null; "clearBehaviorSources"?: boolean }
  limits?: ProactiveLimits
}

export interface MemoryRecallTarget {
  id: string
  version: number
}

export interface MemoryRecallCandidateSnapshot {
  revision: number
  candidatesByScope: { "user": Array<MemoryItem>; "card": Array<MemoryItem>; "session": Array<MemoryItem> }
  candidates: Array<MemoryItem>
  pinned: Array<MemoryItem>
  targeted: Array<MemoryItem>
}

export interface MemoryJobListItem {
  id: string
  phase: "light" | "review"
  status: "queued" | "running" | "paused" | "cancelled" | "completed" | "failed"
  revision: number
  forgetEpoch: number
  leaseUntil: number | null
  processed: number
  createdAt: number
  updatedAt: number
}

export interface MemoryRestorePreview {
  schemaVersion: number
  revision: number
  forgetEpoch: number
  itemCount: number
  jobCount: number
}

export interface MemorySource {
  sourceId: string
  sessionId: string
  entryId: string
  eventId: string
  seq: number
  contentHash: string
  evidence?: string
  sourceLength?: number
  cardId?: string
  eligibleForMemory: boolean
  taint: "trusted_user" | "derived" | "untrusted" | "system"
  origin: "user" | "assistant" | "tool" | "system" | "import" | "derived_behavior"
  observedAt: number
}

export interface MemorySourceAudit {
  sourceId: string
  sessionId: string
  entryId: string
  eventId: string
  seq: number
  contentHash: string
  origin: string
  taint: string
  observedAt: number
}

export interface MemoryHistoryEntry {
  item: MemoryItem
  sourceAudits: Array<MemorySourceAudit>
}

export interface MemoryDraft {
  content: string
  summary: string
  kind: MemoryKind
  scope: MemoryScope
  scopeId?: string
  aliases: Array<string>
  pinned: boolean
  importance: number
  confidence: number
  observedAt?: number
  validFrom?: number | null
  validTo?: number | null
  eventAt?: TemporalAnchor | null
  dueAt?: TemporalAnchor | null
  workingState?: WorkingState
  expiresAt?: number | null
  supersedesId?: string | null
  supersedesIds?: Array<string>
  sourceIds: Array<string>
}

export interface MemoryItem {
  id: string
  version: number
  status: MemoryStatus
  draft: MemoryDraft
  createdAt: number
  updatedAt: number
  origin: MemoryOrigin
}

export interface MemoryJob {
  id: string
  phase: "light" | "review"
  status: "queued" | "running" | "paused" | "cancelled" | "completed" | "failed"
  revision: number
  forgetEpoch: number
  leaseOwner?: string | null
  leaseUntil?: number | null
  cursor?: string
  processed?: number
  createdAt: number
  updatedAt: number
  error?: string
}

export interface MemoryCandidateDraft {
  id?: string
  draft: MemoryDraft
  payloadHash: string
  baseRevision?: number
  reason?: string
}

export type MemoryCommand = "conversation_index_status" | "conversation_index_replace" | "conversation_index_prune" | "conversation_search" | "conversation_context" | "memory_recall_candidates" | "memory_job_list" | "memory_restore_preview" | "memory_source_evidence" | "memory_status" | "memory_list" | "memory_detail" | "memory_history" | "memory_register_sources" | "memory_query" | "memory_get_items" | "memory_apply_change" | "memory_pending_source_count" | "memory_job_start" | "memory_job_checkpoint" | "memory_job_cancel" | "memory_job_resume" | "memory_job_sources" | "memory_candidates_add" | "memory_dreaming_commit" | "memory_dreaming_budget_reserve" | "memory_dreaming_budget_settle" | "memory_dreaming_budget" | "memory_export" | "memory_backup" | "memory_rebuild" | "memory_restore"
export type ProactiveCommand = "proactive_scan" | "proactive_query" | "proactive_change" | "proactive_claim" | "proactive_validate" | "proactive_settle" | "proactive_reconcile" | "proactive_control" | "proactive_auxiliary_budget_reserve" | "proactive_auxiliary_budget_settle"
export const PROACTIVE_LIMITS = Object.freeze({
  "tickMs": 300000,
  "maxTasks": 100,
  "maxRecurringTasks": 10,
  "maxTasksPerPlan": 2,
  "maxTargetsPerMessage": 2,
  "scanBatch": 100,
  "retryDelayMs": 1800000,
  "attemptLeaseMs": 180000,
  "evaluationRetentionDays": 30,
  "settledRetentionDays": 90,
  "tiers": {
    "proactive": {
      "low": {
        "wakeMinMs": 7200000,
        "wakeMaxMs": 18000000,
        "dailySuccess": 2,
        "dailyExpressionAttempts": 4,
        "dailyPlanningAttempts": 3,
        "dailyAuxiliaryAttempts": 2,
        "minSuccessIntervalMs": 10800000,
        "successIntervalSpreadMs": 7200000,
        "dailyTokens": 8000,
        "staySeconds": 120,
        "settleMs": 4000,
        "cooldownMs": 15000,
        "samePageCooldownMs": 20000
      },
      "medium": {
        "wakeMinMs": 1800000,
        "wakeMaxMs": 5400000,
        "dailySuccess": 6,
        "dailyExpressionAttempts": 12,
        "dailyPlanningAttempts": 8,
        "dailyAuxiliaryAttempts": 4,
        "minSuccessIntervalMs": 3600000,
        "successIntervalSpreadMs": 7200000,
        "dailyTokens": 24000,
        "staySeconds": 60,
        "settleMs": 2000,
        "cooldownMs": 5000,
        "samePageCooldownMs": 7800
      },
      "high": {
        "wakeMinMs": 600000,
        "wakeMaxMs": 1800000,
        "dailySuccess": 10,
        "dailyExpressionAttempts": 20,
        "dailyPlanningAttempts": 14,
        "dailyAuxiliaryAttempts": 8,
        "minSuccessIntervalMs": 1800000,
        "successIntervalSpreadMs": 3600000,
        "dailyTokens": 40000,
        "staySeconds": 30,
        "settleMs": 1000,
        "cooldownMs": 3000,
        "samePageCooldownMs": 5000
      }
    },
    "silent": {
      "low": {
        "hours": [
          12,
          20
        ],
        "minBatchGapMs": 7200000,
        "maxReadsPerHour": 4
      },
      "medium": {
        "hours": [
          10,
          14,
          18,
          22
        ],
        "minBatchGapMs": 1800000,
        "maxReadsPerHour": 8
      },
      "high": {
        "hours": [
          9,
          11,
          13,
          15,
          17,
          19
        ],
        "minBatchGapMs": 900000,
        "maxReadsPerHour": 12
      }
    },
    "dreaming": {
      "low": {
        "hours": [
          12,
          20
        ],
        "minIntervalMinutes": 240
      },
      "medium": {
        "hours": [
          10,
          14,
          18,
          22
        ],
        "minIntervalMinutes": 60
      },
      "high": {
        "hours": [
          9,
          11,
          13,
          15,
          17,
          19
        ],
        "minIntervalMinutes": 30
      }
    }
  }
} as const)
export const MEMORY_LIMITS = Object.freeze({
  "conversation": {
    "batchChunks": 512,
    "maxSearchResults": 50
  }
} as const)
