import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { describe, expect, it } from "vitest"
// 脚本是 Node 侧 ESM 工具（scripts/*.mjs）：不在 tsconfig 的 include 里，也没有 .d.ts。
// 按运行期契约导入，形状由下面的 CheckBundleConfig 钉住。
// @ts-expect-error TS7016 —— 只抑制「找不到模块声明」，断言与形状检查照常生效。
import { checkBundleConfig as checkBundleConfigSource, resolveTag as resolveTagSource } from "../../../scripts/check-bundle-config.mjs"

/** 校验器的运行期契约（与 scripts/check-bundle-config.mjs 的导出一致）。 */
type CheckBundleConfig = (rootDir: string, options?: { tag?: string | null }) => string[]
const checkBundleConfig: CheckBundleConfig = checkBundleConfigSource

/** tag 解析器的运行期契约。 */
type ResolveTag = (env: Record<string, string | undefined>, argv: string[]) => string | null
const resolveTag: ResolveTag = resolveTagSource

interface FixtureOptions {
  config?: unknown
  icons?: string[]
  /** 覆盖默认 config 的 productName（默认 ASCII；非 ASCII 会进产物文件名，被 GitHub 剥掉） */
  productName?: string
  updaterPubkey?: string | null
  /** 覆盖默认 config 的 version（只影响未显式传 config 的夹具） */
  confVersion?: string
  /** 单独覆盖 package.json / Cargo.toml 的 version，用来构造「三处不一致」 */
  packageVersion?: string
  cargoVersion?: string
  /** Cargo.lock 里 tauri crate 的解析版本（默认与 JS 侧对齐） */
  tauriCrateVersion?: string
  /** pnpm-lock.yaml 里 @tauri-apps/api 的解析版本；给多个值构造「同一包锁成两个版本」的漂移 */
  tauriApiVersions?: string[]
  /** package.json 里 @tauri-apps/api 的声明范围；默认按解析版本生成 caret range */
  tauriApiSpecifier?: string
}

function fixtureRoot(options: FixtureOptions = {}) {
  const root = mkdtempSync(join(tmpdir(), "bundle-config-"))
  mkdirSync(join(root, "src-tauri", "icons"), { recursive: true })
  for (const name of options.icons ?? ["32x32.png", "128x128.png", "icon.icns", "icon.ico"]) {
    writeFileSync(join(root, "src-tauri", "icons", name), "x")
  }
  const config = options.config ?? {
    productName: options.productName ?? "v1rtual-desk-pet",
    version: options.confVersion ?? "0.15.0",
    identifier: "com.v1rtual.deskpet",
    bundle: {
      active: true,
      targets: "all",
      icon: ["icons/32x32.png", "icons/128x128.png", "icons/icon.icns", "icons/icon.ico"],
      resources: { "resources/defaults": "defaults" },
    },
    plugins: {
      updater: {
        pubkey: options.updaterPubkey === undefined ? "dW50cnVzdGVkIGNvbW1lbnQ6" : options.updaterPubkey,
        endpoints: ["https://github.com/V1rtual-Klavte/Desk-Pet/releases/latest/download/latest.json"],
      },
    },
  }
  writeFileSync(join(root, "src-tauri", "tauri.conf.json"), JSON.stringify(config, null, 2))

  // 三处版本号默认与 config 的 version 联动；[dependencies] 里的嵌套 version 离行首，
  // 用来钉住「只认 [package] 段的行首 version」这条口径。
  const confVersionRaw = (config as { version?: unknown }).version
  const baseVersion = typeof confVersionRaw === "string" ? confVersionRaw : "0.15.0"
  const apiVersions = options.tauriApiVersions ?? ["2.12.1"]
  const rootApiVersion = apiVersions[0]
  writeFileSync(
    join(root, "package.json"),
    JSON.stringify(
      {
        name: "deskpet-fixture",
        version: options.packageVersion ?? baseVersion,
        dependencies: {
          "@tauri-apps/api": options.tauriApiSpecifier ?? `^${rootApiVersion}`,
        },
      },
      null,
      2,
    ),
  )
  writeFileSync(
    join(root, "src-tauri", "Cargo.toml"),
    `[package]\nname = "deskpet-fixture"\nversion = "${options.cargoVersion ?? baseVersion}"\nedition = "2021"\n\n` +
    `[dependencies]\nserde = { version = "1.0.0", features = ["derive"] }\n`,
  )
  // 版本对齐的判据只在锁文件的解析结果里：Cargo.toml / package.json 的声明都是 caret range，
  // 允许范围内漂移。默认两边对齐（2.12.1）。
  writeFileSync(
    join(root, "Cargo.lock"),
    [
      "# This file is automatically @generated by Cargo.",
      "# It is not intended for manual editing.",
      "version = 4",
      "",
      "[[package]]",
      'name = "deskpet-fixture"',
      `version = "${baseVersion}"`,
      "",
      "[[package]]",
      'name = "tauri"',
      `version = "${options.tauriCrateVersion ?? "2.12.1"}"`,
      'source = "registry+https://github.com/rust-lang/crates.io-index"',
      'checksum = "0000000000000000000000000000000000000000000000000000000000000000"',
      "",
    ].join("\n"),
  )
  writeFileSync(
    join(root, "pnpm-lock.yaml"),
    [
      "lockfileVersion: '9.0'",
      "",
      "importers:",
      "",
      "  .:",
      "    dependencies:",
      "      '@tauri-apps/api':",
      `        specifier: ${options.tauriApiSpecifier ?? `^${rootApiVersion}`}`,
      `        version: ${rootApiVersion}`,
      "",
      "packages:",
      "",
      ...apiVersions.map(v => `  '@tauri-apps/api@${v}':\n    resolution: {integrity: sha512-fixture}`),
      "",
      "snapshots:",
      "",
      ...apiVersions.map(v => `  '@tauri-apps/api@${v}': {}`),
      "",
    ].join("\n"),
  )
  return root
}

describe("checkBundleConfig", () => {
  it("合规配置零问题", () => {
    expect(checkBundleConfig(fixtureRoot())).toEqual([])
  })

  it("productName 含非 ASCII 字符被拦，点名 GitHub 剥名、latest.json 被跳过的后果", () => {
    // v0.15.0 发布事故：productName 是中文 → 产物文件名带中文 → GitHub 上传时剥掉非 ASCII →
    // tauri-action 匹配不到自己的产物名，静默跳过 updater 的 latest.json：CI 全绿，更新永久失效。
    const problems = checkBundleConfig(fixtureRoot({ productName: "虚拟桌宠" }))
    expect(problems.some(p => p.includes("productName") && p.includes("latest.json"))).toBe(true)
    // 判据必须是「纯 ASCII」而不是「有没有中文」：重音字母同样会被 GitHub 剥掉，只有 ASCII 才安全
    const accented = checkBundleConfig(fixtureRoot({ productName: "café-desk-pet" }))
    expect(accented.some(p => p.includes("productName"))).toBe(true)
  })

  it("图标文件缺失被点名", () => {
    const root = fixtureRoot({ config: undefined, icons: ["32x32.png"] })
    const problems = checkBundleConfig(root)
    expect(problems.some(p => p.includes("128x128.png"))).toBe(true)
    expect(problems.some(p => p.includes("icon.icns"))).toBe(true)
  })

  it("targets 写死单一平台目标被拦（本次要修的原始 bug）", () => {
    const root = fixtureRoot({
      config: {
        productName: "v1rtual-desk-pet", version: "0.15.0", identifier: "com.v1rtual.deskpet",
        bundle: { active: true, targets: ["nsis"], icon: ["icons/32x32.png"], resources: {} },
        plugins: { updater: { pubkey: "k", endpoints: ["https://example.com/latest.json"] } },
      },
    })
    const problems = checkBundleConfig(root)
    expect(problems.some(p => p.includes("targets"))).toBe(true)
  })

  it("identifier 不是反向域名被拦", () => {
    const root = fixtureRoot({
      config: {
        productName: "v1rtual-desk-pet", version: "0.15.0", identifier: "deskpet",
        bundle: { active: true, targets: "all", icon: ["icons/32x32.png"], resources: {} },
        plugins: { updater: { pubkey: "k", endpoints: ["https://example.com/latest.json"] } },
      },
    })
    expect(checkBundleConfig(root).some(p => p.includes("identifier"))).toBe(true)
  })

  it("updater 公钥为空被拦", () => {
    const root = fixtureRoot({ updaterPubkey: "" })
    expect(checkBundleConfig(root).some(p => p.includes("pubkey"))).toBe(true)
  })

  it("tag 与 version 不一致被拦，一致则通过", () => {
    const root = fixtureRoot()
    expect(checkBundleConfig(root, { tag: "v0.15.0" })).toEqual([])
    const problems = checkBundleConfig(root, { tag: "v0.16.0" })
    expect(problems.some(p => p.includes("version:set"))).toBe(true)
  })

  it("package.json 的 version 与其它两处不一致被拦，点名文件并给出 version:set 修法", () => {
    const root = fixtureRoot({ packageVersion: "0.16.0" })
    const problems = checkBundleConfig(root)
    expect(problems.some(p => p.includes("package.json") && p.includes("version:set"))).toBe(true)
  })

  it("Cargo.toml 的 version 与其它两处不一致被拦，点名文件并给出 version:set 修法", () => {
    const root = fixtureRoot({ cargoVersion: "0.16.0" })
    const problems = checkBundleConfig(root)
    expect(problems.some(p => p.includes("Cargo.toml") && p.includes("version:set"))).toBe(true)
  })

  it("tag 校验逐文件覆盖三处，tauri.conf.json 与 tag 不一致也被点名", () => {
    // 三处一致（0.16.0）但与 tag 不符：两两对照无话可说，只有 tag 逐文件核对能报出，
    // 三处必须各报一条，不能只查 tauri.conf.json。
    const root = fixtureRoot({ confVersion: "0.16.0" })
    const problems = checkBundleConfig(root, { tag: "v0.15.0" })
    expect(problems.filter(p => p.includes("tag v0.15.0"))).toHaveLength(3)
    expect(problems.some(p => p.includes("tauri.conf.json") && p.includes("version:set"))).toBe(true)
  })

  it("Cargo.lock 的 tauri crate 与 pnpm-lock.yaml 的 @tauri-apps/api 同 major.minor 时零问题（补丁号可不同）", () => {
    const root = fixtureRoot({ tauriCrateVersion: "2.12.0", tauriApiVersions: ["2.12.1"] })
    expect(checkBundleConfig(root)).toEqual([])
  })

  it("判据是锁文件的解析版本：package.json 范围放宽（^2.11.1 解析到 2.12.1）不报错", () => {
    // 声明范围与解析结果不是一回事。本次发布事故正是 range 允许、锁文件漂移；
    // 按 range 字面判定会把「声明旧、解析新」的正常状态误报。
    const root = fixtureRoot({ tauriApiSpecifier: "^2.11.1", tauriApiVersions: ["2.12.1"] })
    expect(checkBundleConfig(root)).toEqual([])
  })

  it("tauri crate 与 @tauri-apps/api 跨 minor 时被拦，点名两个解析版本并给出 pnpm add 修法", () => {
    const root = fixtureRoot({
      tauriCrateVersion: "2.12.1",
      tauriApiVersions: ["2.11.1"],
      tauriApiSpecifier: "^2.11.1",
    })
    const hit = checkBundleConfig(root).find(p => p.includes("2.12.1") && p.includes("2.11.1"))
    expect(hit).toBeDefined()
    expect(hit).toContain("pnpm add '@tauri-apps/api@^2.12'")
  })

  it("pnpm-lock.yaml 里 @tauri-apps/api 解析出多个版本时单独报出漂移", () => {
    // 事故形态：新插件把 2.11.1 锁成子依赖，根依赖仍是 2.12.1，tauri build 只认其中一份。
    const root = fixtureRoot({ tauriCrateVersion: "2.12.1", tauriApiVersions: ["2.11.1", "2.12.1"] })
    const problems = checkBundleConfig(root)
    expect(
      problems.some(p => p.includes("解析出多个版本") && p.includes("2.11.1") && p.includes("2.12.1")),
    ).toBe(true)
  })

  it("tauri.conf.json 不是合法 JSON 时给出可读报错", () => {
    const root = fixtureRoot()
    writeFileSync(join(root, "src-tauri", "tauri.conf.json"), "{ 坏掉的 json")
    const problems = checkBundleConfig(root)
    expect(problems).toHaveLength(1)
    expect(problems[0]).toContain("tauri.conf.json")
  })
})

describe("resolveTag", () => {
  it("GITHUB_REF_TYPE 是 branch 时忽略 GITHUB_REF_NAME —— 否则每次 push/PR 都会误报版本不一致", () => {
    expect(resolveTag({ GITHUB_REF_TYPE: "branch", GITHUB_REF_NAME: "master" }, ["node", "script.mjs"])).toBe(null)
    expect(resolveTag({ GITHUB_REF_TYPE: "branch", GITHUB_REF_NAME: "123/merge" }, ["node", "script.mjs"])).toBe(null)
  })

  it("GITHUB_REF_TYPE 是 tag 时取 GITHUB_REF_NAME", () => {
    expect(resolveTag({ GITHUB_REF_TYPE: "tag", GITHUB_REF_NAME: "v0.15.0" }, ["node", "script.mjs"])).toBe("v0.15.0")
  })

  it("没有 GITHUB_REF_TYPE 时回退到位置参数；两者都没有则为 null", () => {
    expect(resolveTag({}, ["node", "script.mjs", "v0.15.0"])).toBe("v0.15.0")
    expect(resolveTag({}, ["node", "script.mjs"])).toBe(null)
  })
})
